/*!
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */
export interface Dimensions {
  height: number;
  width: number;
  depth: number;
}

export interface Author {
  name: string;
  bio: string;
  imageUrl?: string;
}

export interface Publisher {
  name: string;
  location: string;
}

export interface Review {
  username: string;
  rating: number; // 1-5 stars
  comment: string;
  timestamp: string;
}

export interface Award {
  name: string;
  year: number;
  organization: string;
}

export interface Book {
  id: string;
  title: string;
  subtitle?: string;
  authors: Author[];
  publisher: Publisher;
  publicationDate: string;
  isbn: string;
  genres: string[];
  tags: string[];
  description: string;
  language: string;
  format: 'Hardcover' | 'Paperback' | 'eBook' | 'Audiobook';
  pages: number;
  coverImgUrl: string;
  price: number;
  salePrice?: number;
  stock: number;
  averageRating: number;
  reviews: Review[];
  awards?: Award[];
  dimensions: Dimensions;
  series?: {
    name: string;
    number: number;
  };
  edition?: string;
  bestsellerRank?: number;
}

export const DATA: Book[] = [
  {
    id: '1',
    title: 'The Crimson Cipher',
    authors: [{ name: 'Elena Vance', bio: 'Elena Vance is a master of historical thrillers.' }],
    publisher: { name: 'Codex Publishing', location: 'New York' },
    publicationDate: '2023-05-20',
    isbn: '978-0-385-54734-5',
    genres: ['Mystery', 'Thriller'],
    tags: ['historical', 'conspiracy', 'art'],
    description: 'A symbologist must uncover a secret hidden within a Renaissance painting to prevent a global catastrophe.',
    language: 'English',
    format: 'Hardcover',
    pages: 412,
    coverImgUrl: 'cover-art/mystery.png',
    price: 28.99,
    stock: 150,
    averageRating: 4.6,
    reviews: [
      { username: 'ReaderX', rating: 5, comment: 'An absolute masterpiece of suspense!', timestamp: '2023-06-01T10:00:00Z' },
      { username: 'HistoryBuff', rating: 4, comment: 'Well-researched and thrilling.', timestamp: '2023-06-05T14:30:00Z' },
    ],
    awards: [{ name: 'The Golden Quill', year: 2023, organization: 'International Thriller Writers' }],
    dimensions: { height: 9.5, width: 6.4, depth: 1.4 },
    bestsellerRank: 3,
  },
  {
    id: '2',
    title: 'Galactic Echoes',
    authors: [{ name: 'Jax Orion', bio: 'Jax Orion is a visionary sci-fi author.' }],
    publisher: { name: 'Nebula Press', location: 'San Francisco' },
    publicationDate: '2022-11-12',
    isbn: '978-1-9821-3748-8',
    genres: ['Science Fiction'],
    tags: ['space opera', 'AI', 'first contact'],
    description: 'The last human crew on a deep space vessel discovers a signal that could be the key to humanity\'s survival or its ultimate demise.',
    language: 'English',
    format: 'Paperback',
    pages: 528,
    coverImgUrl: 'cover-art/science-fiction.png',
    price: 18.99,
    stock: 200,
    averageRating: 4.8,
    reviews: [
      { username: 'SciFiFanatic', rating: 5, comment: 'A modern classic of the genre.', timestamp: '2022-12-10T18:00:00Z' },
      { username: 'AstroReader', rating: 5, comment: 'Mind-bending concepts and unforgettable characters.', timestamp: '2023-01-15T12:00:00Z' },
    ],
    series: { name: 'The Starlight Chronicles', number: 1 },
    dimensions: { height: 8.2, width: 5.5, depth: 1.2 },
  },
  {
    id: '3',
    title: 'The Whispering Woods',
    authors: [{ name: 'Lyra Meadowlight', bio: 'Lyra Meadowlight writes enchanting fantasy tales.' }],
    publisher: { name: 'Fable & Fern', location: 'Portland' },
    publicationDate: '2024-02-14',
    isbn: '978-0-7653-7646-7',
    genres: ['Fantasy'],
    tags: ['magic', 'folklore', 'adventure'],
    description: 'A young herbalist must venture into a sentient forest to find a cure for her village\'s mysterious illness, guided only by ancient legends.',
    language: 'English',
    format: 'Hardcover',
    pages: 380,
    coverImgUrl: 'cover-art/fantasy.png',
    price: 26.99,
    stock: 120,
    averageRating: 4.5,
    reviews: [
      { username: 'FantasyLover', rating: 5, comment: 'Pure magic from start to finish.', timestamp: '2024-03-01T16:00:00Z' },
    ],
    dimensions: { height: 9.0, width: 6.0, depth: 1.3 },
  },
  {
    id: '4',
    title: 'The Statesman\'s Secret',
    authors: [{ name: 'Marcus Thorne', bio: 'Marcus Thorne is a former diplomat and political analyst.' }],
    publisher: { name: 'Capitol Books', location: 'Washington D.C.' },
    publicationDate: '2023-09-05',
    isbn: '978-1-5011-7134-4',
    genres: ['Political Thriller'],
    tags: ['espionage', 'politics', 'suspense'],
    description: 'A veteran CIA operative uncovers a conspiracy that reaches the highest levels of the U.S. government.',
    language: 'English',
    format: 'Paperback',
    pages: 450,
    coverImgUrl: 'cover-art/political-thriller.png',
    price: 17.99,
    stock: 180,
    averageRating: 4.4,
    reviews: [
      { username: 'DCInsider', rating: 5, comment: 'Chillingly realistic and incredibly tense.', timestamp: '2023-09-20T11:00:00Z' },
    ],
    dimensions: { height: 8.5, width: 5.5, depth: 1.1 },
  },
  {
    id: '5',
    title: 'The Last Voyage of the Stardust',
    authors: [{ name: 'Jax Orion', bio: 'Jax Orion is a visionary sci-fi author.' }],
    publisher: { name: 'Nebula Press', location: 'San Francisco' },
    publicationDate: '2024-01-16',
    isbn: '978-1-9821-3750-1',
    genres: ['Science Fiction'],
    tags: ['space opera', 'AI', 'mystery'],
    description: 'Following the events of Galactic Echoes, the crew of the Stardust is hailed as heroes, but a new, more insidious threat emerges from the shadows of their past.',
    language: 'English',
    format: 'Paperback',
    pages: 550,
    coverImgUrl: 'cover-art/science-fiction.png',
    price: 19.99,
    stock: 250,
    averageRating: 4.9,
    reviews: [
        { username: 'SciFiFanatic', rating: 5, comment: 'A stunning sequel. The stakes are even higher!', timestamp: '2024-02-01T10:00:00Z' },
        { username: 'AstroReader', rating: 5, comment: 'Orion has done it again. A must-read for any sci-fi fan.', timestamp: '2024-02-05T15:30:00Z' },
    ],
    series: { name: 'The Starlight Chronicles', number: 2 },
    dimensions: { height: 8.2, width: 5.5, depth: 1.3 },
    bestsellerRank: 1,
  },
  {
    id: '6',
    title: 'The Gilded Cage',
    authors: [{ name: 'Genevieve Dubois', bio: 'Genevieve Dubois is a historian specializing in the French Revolution.' }],
    publisher: { name: 'Versailles Press', location: 'Paris' },
    publicationDate: '2023-07-14',
    isbn: '978-0-143-13373-0',
    genres: ['Biography'],
    tags: ['history', 'french revolution', 'royalty'],
    description: 'A gripping biography of a lesser-known noblewoman caught in the turmoil of the French Revolution, navigating a world of opulence and terror.',
    language: 'English',
    format: 'Hardcover',
    pages: 480,
    coverImgUrl: 'cover-art/biography.png',
    price: 32.00,
    stock: 90,
    averageRating: 4.7,
    reviews: [
        { username: 'HistoryNerd', rating: 5, comment: 'Impeccably researched and beautifully written. Brings the era to life.', timestamp: '2023-08-01T12:00:00Z' },
        { username: 'ParisianReader', rating: 4, comment: 'A fascinating look into a turbulent time.', timestamp: '2023-08-10T19:00:00Z' },
    ],
    dimensions: { height: 9.6, width: 6.5, depth: 1.6 },
  },
  {
    id: '7',
    title: 'The Way of the Wandering Star',
    authors: [{ name: 'Kaelen Rourke', bio: 'Kaelen Rourke is a travel writer and philosopher.' }],
    publisher: { name: 'Odyssey Books', location: 'Dublin' },
    publicationDate: '2022-09-22',
    isbn: '978-1-64049-421-1',
    genres: ['Travel', 'Philosophy'],
    tags: ['memoir', 'adventure', 'spirituality'],
    description: 'A solo traveler\'s journey across the Himalayas, exploring ancient philosophies and the boundless nature of the human spirit.',
    language: 'English',
    format: 'Paperback',
    pages: 320,
    coverImgUrl: 'cover-art/travel.png',
    price: 16.99,
    stock: 130,
    averageRating: 4.5,
    reviews: [
        { username: 'Wanderlust', rating: 5, comment: 'Inspiring and profoundly moving. Makes you want to pack your bags immediately.', timestamp: '2022-10-15T09:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 0.9 },
  },
  {
    id: '8',
    title: 'The Last Recipe',
    authors: [{ name: 'Isabella Rossi', bio: 'Isabella Rossi is a world-renowned chef and restaurateur.' }],
    publisher: { name: 'Gourmand Press', location: 'Florence' },
    publicationDate: '2023-10-10',
    isbn: '978-0-399-58201-2',
    genres: ['Cooking'],
    tags: ['italian cuisine', 'cookbook', 'memoir'],
    description: 'A collection of cherished family recipes passed down through generations, woven together with stories of love, loss, and the magic of the Italian kitchen.',
    language: 'English',
    format: 'Hardcover',
    pages: 304,
    coverImgUrl: 'cover-art/cooking.png',
    price: 35.00,
    stock: 110,
    averageRating: 4.9,
    reviews: [
        { username: 'FoodieForLife', rating: 5, comment: 'More than a cookbook, it\'s a love letter to food and family. The recipes are divine!', timestamp: '2023-11-01T13:00:00Z' },
    ],
    dimensions: { height: 10.2, width: 8.3, depth: 1.1 },
  },
  {
    id: '9',
    title: 'The Sunstone Prophecy',
    authors: [{ name: 'Lyra Meadowlight', bio: 'Lyra Meadowlight writes enchanting fantasy tales.' }],
    publisher: { name: 'Fable & Fern', location: 'Portland' },
    publicationDate: '2025-01-20',
    isbn: '978-0-7653-7648-1',
    genres: ['Fantasy'],
    tags: ['magic', 'prophecy', 'adventure'],
    description: 'The sequel to The Whispering Woods. The fate of the enchanted forest rests on a new prophecy, one that foretells a looming darkness and a hero who must rise to meet it.',
    language: 'English',
    format: 'Hardcover',
    pages: 400,
    coverImgUrl: 'cover-art/fantasy.png',
    price: 27.99,
    stock: 150,
    averageRating: 0,
    reviews: [],
    series: { name: 'The Forest Chronicles', number: 2 },
    dimensions: { height: 9.0, width: 6.0, depth: 1.4 },
  },
  {
    id: '10',
    title: 'The Art of Stillness',
    authors: [{ name: 'Master Jin', bio: 'Master Jin is a Zen philosopher and meditation guide.' }],
    publisher: { name: 'Mindful Path', location: 'Kyoto' },
    publicationDate: '2021-04-15',
    isbn: '978-1-61180-804-4',
    genres: ['Self-Help', 'Philosophy'],
    tags: ['mindfulness', 'meditation', 'zen'],
    description: 'A practical guide to finding peace and clarity in a chaotic world. Master Jin offers timeless wisdom and simple exercises to cultivate inner stillness.',
    language: 'English',
    format: 'Paperback',
    pages: 224,
    coverImgUrl: 'cover-art/philosophy.png',
    price: 15.95,
    stock: 300,
    averageRating: 4.8,
    reviews: [
        { username: 'ZenSeeker', rating: 5, comment: 'This book changed my life. A must-read for anyone seeking calm.', timestamp: '2021-05-10T14:00:00Z' },
        { username: 'MindfulReader', rating: 5, comment: 'Simple, profound, and incredibly effective.', timestamp: '2021-06-02T11:30:00Z' },
    ],
    dimensions: { height: 7.5, width: 5.0, depth: 0.7 },
  },
  {
    id: '11',
    title: 'Echoes of the Forgotten',
    authors: [{ name: 'Adrian Valerius', bio: 'Adrian Valerius is an archaeologist and historian.' }],
    publisher: { name: 'Antiquarian Press', location: 'Rome' },
    publicationDate: '2023-03-12',
    isbn: '978-0-525-53971-2',
    genres: ['Mystery', 'Biography'],
    tags: ['archaeology', 'ancient rome', 'historical mystery'],
    description: 'An archaeologist uncovers a series of artifacts that challenge the accepted history of the Roman Empire, leading him down a dangerous path of discovery.',
    language: 'English',
    format: 'Hardcover',
    pages: 432,
    coverImgUrl: 'cover-art/biography.png',
    price: 29.99,
    stock: 80,
    averageRating: 4.6,
    reviews: [
        { username: 'HistoryGeek', rating: 5, comment: 'A perfect blend of history and suspense. I couldn\'t put it down!', timestamp: '2023-04-01T18:00:00Z' },
    ],
    dimensions: { height: 9.5, width: 6.4, depth: 1.5 },
  },
  {
    id: '12',
    title: 'The Girl Who Talked to Trees',
    authors: [{ name: 'Penelope Bloom', bio: 'Penelope Bloom writes heartwarming stories for young readers.' }],
    publisher: { name: 'Little Sprouts Books', location: 'Asheville' },
    publicationDate: '2022-08-20',
    isbn: '978-1-5344-9924-5',
    genres: ['Childrens', 'Young Adult'],
    tags: ['nature', 'friendship', 'magic'],
    description: 'A young girl with a special ability to communicate with nature must rally her forest friends to save their home from developers.',
    language: 'English',
    format: 'Hardcover',
    pages: 256,
    coverImgUrl: 'cover-art/childrens.png',
    price: 17.99,
    stock: 150,
    averageRating: 4.9,
    reviews: [
        { username: 'ParentReader', rating: 5, comment: 'A beautiful story with a wonderful message. My kids loved it!', timestamp: '2022-09-10T20:00:00Z' },
    ],
    dimensions: { height: 8.5, width: 6.0, depth: 1.0 },
  },
  {
    id: '13',
    title: 'Operation Nightfall',
    authors: [{ name: 'Colonel Rex "Havoc" Stone', bio: 'Colonel Rex Stone is a decorated special forces veteran.' }],
    publisher: { name: 'Stealth Publishing', location: 'San Diego' },
    publicationDate: '2023-11-07',
    isbn: '978-0-399-59341-4',
    genres: ['Military Thriller'],
    tags: ['special forces', 'action', 'counter-terrorism'],
    description: 'A retired Navy SEAL is called back for one last impossible mission: to stop a rogue faction from unleashing a new type of chemical weapon.',
    language: 'English',
    format: 'Paperback',
    pages: 384,
    coverImgUrl: 'cover-art/military-thriller.png',
    price: 16.99,
    stock: 220,
    averageRating: 4.5,
    reviews: [
        { username: 'ActionJunkie', rating: 5, comment: 'Non-stop action from a guy who has been there. Authentic and thrilling.', timestamp: '2023-11-20T17:00:00Z' },
    ],
    dimensions: { height: 8.2, width: 5.5, depth: 1.0 },
  },
  {
    id: '14',
    title: 'The Summer House on the Lake',
    authors: [{ name: 'Juliette Rose', bio: 'Juliette Rose writes sweeping, emotional love stories.' }],
    publisher: { name: 'Evergreen Romance', location: 'Charleston' },
    publicationDate: '2024-06-11',
    isbn: '978-0-593-33531-1',
    genres: ['Romance'],
    tags: ['summer romance', 'second chances', 'contemporary'],
    description: 'Two childhood sweethearts, now leading separate lives, are unexpectedly reunited at their families\' shared lake house. Old sparks fly, but new secrets stand in their way.',
    language: 'English',
    format: 'Paperback',
    pages: 352,
    coverImgUrl: 'cover-art/romance.png',
    price: 17.00,
    stock: 300,
    averageRating: 0,
    reviews: [],
    dimensions: { height: 8.0, width: 5.2, depth: 0.9 },
  },
  {
    id: '15',
    title: 'The Alchemist of Prague',
    authors: [{ name: 'Elena Vance', bio: 'Elena Vance is a master of historical thrillers.' }],
    publisher: { name: 'Codex Publishing', location: 'New York' },
    publicationDate: '2025-03-18',
    isbn: '978-0-385-54736-9',
    genres: ['Mystery', 'Thriller'],
    tags: ['historical', 'alchemy', 'prague'],
    description: 'In the gaslit streets of 19th-century Prague, a brilliant detective must hunt a killer who uses the ancient art of alchemy to commit impossible murders.',
    language: 'English',
    format: 'Hardcover',
    pages: 430,
    coverImgUrl: 'cover-art/mystery.png',
    price: 29.99,
    stock: 100,
    averageRating: 0,
    reviews: [],
    dimensions: { height: 9.5, width: 6.4, depth: 1.5 },
  },
  {
    id: '16',
    title: 'The Last Starchild',
    authors: [{ name: 'Orion Blackwood', bio: 'Orion Blackwood is a fresh voice in young adult fantasy.' }],
    publisher: { name: 'Moonbeam Books', location: 'London' },
    publicationDate: '2023-08-15',
    isbn: '978-1-4088-5566-9',
    genres: ['Young Adult', 'Fantasy'],
    tags: ['magic', 'coming of age', 'destiny'],
    description: 'A teenager discovers she is the last of a celestial line, gifted with star-magic, and must learn to control her powers to save her world from an encroaching darkness.',
    language: 'English',
    format: 'Paperback',
    pages: 384,
    coverImgUrl: 'cover-art/young-adult.png',
    price: 14.99,
    stock: 180,
    averageRating: 4.7,
    reviews: [
        { username: 'YAFan', rating: 5, comment: 'An incredible start to a new series. I\'m hooked!', timestamp: '2023-09-01T11:00:00Z' },
    ],
    dimensions: { height: 7.8, width: 5.1, depth: 1.0 },
  },
  {
    id: '17',
    title: 'The Quantum Paradox',
    authors: [{ name: 'Dr. Evelyn Reed', bio: 'Dr. Evelyn Reed is a theoretical physicist and science communicator.' }],
    publisher: { name: 'Helix Books', location: 'Cambridge' },
    publicationDate: '2022-10-04',
    isbn: '978-0-593-23744-5',
    genres: ['Science Fiction'],
    tags: ['hard sci-fi', 'time travel', 'physics'],
    description: 'A team of physicists accidentally opens a rift in spacetime, and must navigate the paradoxes of their own past and future to close it before reality unravels.',
    language: 'English',
    format: 'Hardcover',
    pages: 464,
    coverImgUrl: 'cover-art/science-fiction.png',
    price: 28.00,
    stock: 95,
    averageRating: 4.6,
    reviews: [
        { username: 'PhysicsNerd', rating: 5, comment: 'Finally, a time travel story that respects the science! Brilliantly executed.', timestamp: '2022-10-20T15:00:00Z' },
    ],
    dimensions: { height: 9.3, width: 6.3, depth: 1.6 },
  },
  {
    id: '18',
    title: 'The Dragon\'s Tooth',
    authors: [{ name: 'Gideon Drake', bio: 'Gideon Drake writes epic fantasy for a new generation.' }],
    publisher: { name: 'Wyrmwood Press', location: 'Edinburgh' },
    publicationDate: '2023-06-21',
    isbn: '978-0-7653-8968-9',
    genres: ['Fantasy', 'RPG-Lit'],
    tags: ['dragons', 'magic items', 'epic fantasy'],
    description: 'A disgraced knight must assemble a band of heroes to retrieve a legendary artifact, the Dragon\'s Tooth, before it falls into the hands of a tyrannical sorcerer.',
    language: 'English',
    format: 'Paperback',
    pages: 624,
    coverImgUrl: 'cover-art/rpg-lit.png',
    price: 19.99,
    stock: 210,
    averageRating: 4.8,
    reviews: [
        { username: 'EpicFantasyFan', rating: 5, comment: 'A grand adventure with classic fantasy elements done right. The magic system is incredible.', timestamp: '2023-07-10T12:00:00Z' },
    ],
    series: { name: 'The Artifacts of Power', number: 1 },
    dimensions: { height: 8.5, width: 5.5, depth: 1.5 },
  },
  {
    id: '19',
    title: 'The Resilient Mind',
    authors: [{ name: 'Dr. Anya Sharma', bio: 'Dr. Anya Sharma is a clinical psychologist and expert in cognitive behavioral therapy.' }],
    publisher: { name: 'Mindful Path', location: 'Kyoto' },
    publicationDate: '2023-01-30',
    isbn: '978-1-61180-933-1',
    genres: ['Self-Help'],
    tags: ['psychology', 'resilience', 'mental health'],
    description: 'A practical, evidence-based guide to building mental fortitude, overcoming adversity, and thriving in the face of life\'s challenges.',
    language: 'English',
    format: 'Paperback',
    pages: 288,
    coverImgUrl: 'cover-art/self-help.png',
    price: 18.95,
    stock: 250,
    averageRating: 4.9,
    reviews: [
        { username: 'BetterMe', rating: 5, comment: 'An incredibly useful and compassionate book. The techniques are easy to apply and really work.', timestamp: '2023-02-20T10:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 0.8 },
  },
  {
    id: '20',
    title: 'The Clockwork City',
    authors: [{ name: 'Silas Cogsworth', bio: 'Silas Cogsworth is an imaginative writer of steampunk adventures.' }],
    publisher: { name: 'Brass & Bolt Books', location: 'London' },
    publicationDate: '2022-04-19',
    isbn: '978-1-939899-42-7',
    genres: ['Fantasy', 'Science Fiction'],
    tags: ['steampunk', 'invention', 'mystery'],
    description: 'In a city powered by steam and clockwork, a brilliant inventor is framed for a crime she didn\'t commit. To clear her name, she must navigate a world of airships, automatons, and political intrigue.',
    language: 'English',
    format: 'Paperback',
    pages: 416,
    coverImgUrl: 'cover-art/fantasy.png',
    price: 16.99,
    stock: 140,
    averageRating: 4.4,
    reviews: [
        { username: 'SteampunkFan', rating: 5, comment: 'A fantastic steampunk world with a gripping mystery. Highly recommended!', timestamp: '2022-05-05T16:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 1.1 },
  },
  {
    id: '21',
    title: 'The Bone Orchard',
    authors: [{ name: 'Seraphina Cross', bio: 'Seraphina Cross writes dark, atmospheric mysteries.' }],
    publisher: { name: 'Gallows Press', location: 'New Orleans' },
    publicationDate: '2023-04-11',
    isbn: '978-0-593-31043-1',
    genres: ['Mystery', 'Thriller'],
    tags: ['gothic', 'southern gothic', 'supernatural'],
    description: 'A detective with a troubled past returns to her Louisiana hometown to solve a series of ritualistic murders that are eerily connected to a local legend.',
    language: 'English',
    format: 'Paperback',
    pages: 368,
    coverImgUrl: 'cover-art/mystery.png',
    price: 17.99,
    stock: 160,
    averageRating: 4.5,
    reviews: [
        { username: 'GothicReader', rating: 5, comment: 'Chilling, atmospheric, and beautifully written. I couldn\'t sleep!', timestamp: '2023-04-25T22:00:00Z' },
    ],
    dimensions: { height: 8.2, width: 5.5, depth: 1.0 },
  },
  {
    id: '22',
    title: 'The Cartographer of Dreams',
    authors: [{ name: 'Finnian Quill', bio: 'Finnian Quill is a writer of lyrical and imaginative tales.' }],
    publisher: { name: 'Ink & Compass', location: 'Dublin' },
    publicationDate: '2022-07-19',
    isbn: '978-1-5247-6201-3',
    genres: ['Fantasy'],
    tags: ['maps', 'magic', 'adventure', 'folklore'],
    description: 'A young apprentice discovers he can map people\'s dreams, a talent that draws him into a hidden world of dream-weavers and nightmare-hunters.',
    language: 'English',
    format: 'Hardcover',
    pages: 352,
    coverImgUrl: 'cover-art/fantasy.png',
    price: 25.99,
    stock: 110,
    averageRating: 4.6,
    reviews: [
        { username: 'Dreamer', rating: 5, comment: 'A wholly original and enchanting story. Pure magic.', timestamp: '2022-08-05T14:00:00Z' },
    ],
    dimensions: { height: 8.8, width: 5.9, depth: 1.3 },
  },
  {
    id: '23',
    title: 'The Zero-G Heist',
    authors: [{ name: 'Cora "Comet" Chen', bio: 'Cora Chen is a former aerospace engineer turned sci-fi author.' }],
    publisher: { name: 'Orbital Publishing', location: 'Houston' },
    publicationDate: '2023-02-28',
    isbn: '978-0-593-44112-8',
    genres: ['Science Fiction', 'Thriller'],
    tags: ['heist', 'space station', 'action'],
    description: 'A team of ex-convicts is assembled to pull off the most audacious heist in history: robbing a casino on a luxury space station. The only catch? They have to do it in zero gravity.',
    language: 'English',
    format: 'Paperback',
    pages: 400,
    coverImgUrl: 'cover-art/science-fiction.png',
    price: 18.00,
    stock: 190,
    averageRating: 4.3,
    reviews: [
        { username: 'ActionFan', rating: 4, comment: 'Ocean\'s Eleven in space. A fun, high-octane ride.', timestamp: '2023-03-15T19:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 1.1 },
  },
  {
    id: '24',
    title: 'The Emperor\'s Shadow',
    authors: [{ name: 'Kenji Tanaka', bio: 'Kenji Tanaka is a historian and author specializing in feudal Japan.' }],
    publisher: { name: 'Bushido Books', location: 'Kyoto' },
    publicationDate: '2021-11-30',
    isbn: '978-4-06-521833-8',
    genres: ['Biography'],
    tags: ['samurai', 'history', 'japan', 'war'],
    description: 'The epic biography of a legendary samurai who served as the secret protector of the emperor during a time of civil war and political upheaval.',
    language: 'English',
    format: 'Hardcover',
    pages: 512,
    coverImgUrl: 'cover-art/biography.png',
    price: 34.99,
    stock: 70,
    averageRating: 4.9,
    reviews: [
        { username: 'SamuraiSteve', rating: 5, comment: 'A masterpiece of historical biography. Reads like an epic novel.', timestamp: '2021-12-20T13:00:00Z' },
    ],
    dimensions: { height: 9.6, width: 6.5, depth: 1.8 },
  },
  {
    id: '25',
    title: 'The Little Bear Who Lost His Roar',
    authors: [{ name: 'Daisy Meadows', bio: 'Daisy Meadows creates charming stories for the littlest readers.' }],
    publisher: { name: 'Little Sprouts Books', location: 'Asheville' },
    publicationDate: '2023-09-12',
    isbn: '978-1-5344-9926-9',
    genres: ['Childrens'],
    tags: ['animals', 'friendship', 'self-discovery'],
    description: 'A little bear wakes up one morning to find his mighty roar has been replaced by a tiny squeak! He embarks on a journey through the forest to find it, making new friends along the way.',
    language: 'English',
    format: 'Hardcover',
    pages: 32,
    coverImgUrl: 'cover-art/childrens.png',
    price: 16.99,
    stock: 200,
    averageRating: 4.8,
    reviews: [
        { username: 'MomOfTwo', rating: 5, comment: 'An adorable story with beautiful illustrations. My toddler asks for it every night.', timestamp: '2023-10-01T19:30:00Z' },
    ],
    dimensions: { height: 9.0, width: 9.0, depth: 0.5 },
  },
  {
    id: '26',
    title: 'The Phoenix Protocol',
    authors: [{ name: 'Marcus Thorne', bio: 'Marcus Thorne is a former diplomat and political analyst.' }],
    publisher: { name: 'Capitol Books', location: 'Washington D.C.' },
    publicationDate: '2024-09-03',
    isbn: '978-1-5011-7136-8',
    genres: ['Political Thriller'],
    tags: ['cyberterrorism', 'politics', 'conspiracy'],
    description: 'A devastating cyberattack cripples the nation\'s infrastructure, and the operative from The Statesman\'s Secret is the only one who knows it\'s just the beginning of a much larger plot.',
    language: 'English',
    format: 'Paperback',
    pages: 464,
    coverImgUrl: 'cover-art/political-thriller.png',
    price: 18.99,
    stock: 200,
    averageRating: 0,
    reviews: [],
    series: { name: 'The Operative', number: 2 },
    dimensions: { height: 8.5, width: 5.5, depth: 1.2 },
  },
  {
    id: '27',
    title: 'The Secret Garden of Words',
    authors: [{ name: 'Eleanor Vance', bio: 'Eleanor Vance is a poet and novelist.' }],
    publisher: { name: 'Evergreen Romance', location: 'Charleston' },
    publicationDate: '2022-05-17',
    isbn: '978-0-593-33529-8',
    genres: ['Romance'],
    tags: ['books', 'love', 'ireland', 'contemporary'],
    description: 'A reclusive author with writer\'s block inherits a charming, chaotic bookstore in a small Irish village. There, she discovers a lost manuscript that leads her to an unexpected love.',
    language: 'English',
    format: 'Paperback',
    pages: 336,
    coverImgUrl: 'cover-art/romance.png',
    price: 16.00,
    stock: 180,
    averageRating: 4.6,
    reviews: [
        { username: 'Bookworm', rating: 5, comment: 'A love letter to books and book lovers. Absolutely charming.', timestamp: '2022-06-01T15:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 0.9 },
  },
  {
    id: '28',
    title: 'The Nomad\'s Compass',
    authors: [{ name: 'Asher Grey', bio: 'Asher Grey is a globetrotter who documents his journeys in vivid prose.' }],
    publisher: { name: 'Odyssey Books', location: 'Dublin' },
    publicationDate: '2023-11-21',
    isbn: '978-1-64049-423-5',
    genres: ['Travel'],
    tags: ['adventure', 'memoir', 'sailing', 'exploration'],
    description: 'The incredible true story of a man who sold everything he owned to sail around the world, navigating by the stars and the kindness of strangers.',
    language: 'English',
    format: 'Paperback',
    pages: 368,
    coverImgUrl: 'cover-art/travel.png',
    price: 17.99,
    stock: 140,
    averageRating: 4.7,
    reviews: [
        { username: 'Sailor', rating: 5, comment: 'A breathtaking journey of courage and discovery. Truly inspiring.', timestamp: '2023-12-10T10:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 1.0 },
  },
  {
    id: '29',
    title: 'The Rebel King',
    authors: [{ name: 'Orion Blackwood', bio: 'Orion Blackwood is a fresh voice in young adult fantasy.' }],
    publisher: { name: 'Moonbeam Books', location: 'London' },
    publicationDate: '2024-08-13',
    isbn: '978-1-4088-5568-3',
    genres: ['Young Adult', 'Fantasy'],
    tags: ['magic', 'rebellion', 'royalty'],
    description: 'In the sequel to The Last Starchild, the young celestial must now lead a rebellion against the dark forces that have conquered her kingdom, all while wrestling with her own immense power.',
    language: 'English',
    format: 'Paperback',
    pages: 400,
    coverImgUrl: 'cover-art/young-adult.png',
    price: 15.99,
    stock: 200,
    averageRating: 0,
    reviews: [],
    series: { name: 'The Starchild Saga', number: 2 },
    dimensions: { height: 7.8, width: 5.1, depth: 1.1 },
  },
  {
    id: '30',
    title: 'The Spice of Life: A Culinary Manifesto',
    authors: [{ name: 'Chef Antoine Dubois', bio: 'Chef Antoine Dubois is a culinary revolutionary known for his bold flavors.' }],
    publisher: { name: 'Gourmand Press', location: 'Florence' },
    publicationDate: '2022-03-08',
    isbn: '978-0-399-58203-6',
    genres: ['Cooking'],
    tags: ['global cuisine', 'spices', 'cookbook', 'essays'],
    description: 'A vibrant exploration of spices from around the world, featuring 150 recipes that will transform your cooking from mundane to magnificent. Part cookbook, part travelogue.',
    language: 'English',
    format: 'Hardcover',
    pages: 352,
    coverImgUrl: 'cover-art/cooking.png',
    price: 37.50,
    stock: 90,
    averageRating: 4.8,
    reviews: [
        { username: 'SpiceMaster', rating: 5, comment: 'A stunning book. The photography is gorgeous and the recipes are inventive and delicious.', timestamp: '2022-03-25T18:00:00Z' },
    ],
    dimensions: { height: 10.5, width: 8.5, depth: 1.2 },
  },
  {
    id: '31',
    title: 'The Aegis Gambit',
    authors: [{ name: 'Colonel Rex "Havoc" Stone', bio: 'Colonel Rex Stone is a decorated special forces veteran.' }],
    publisher: { name: 'Stealth Publishing', location: 'San Diego' },
    publicationDate: '2024-11-05',
    isbn: '978-0-399-59343-8',
    genres: ['Military Thriller'],
    tags: ['special forces', 'geopolitical', 'action'],
    description: 'When a next-generation missile defense system is stolen, the hero of Operation Nightfall must lead a deniable ops team to retrieve it before it can be used to start World War III.',
    language: 'English',
    format: 'Paperback',
    pages: 400,
    coverImgUrl: 'cover-art/military-thriller.png',
    price: 17.99,
    stock: 250,
    averageRating: 0,
    reviews: [],
    series: { name: 'Havoc', number: 2 },
    dimensions: { height: 8.2, width: 5.5, depth: 1.1 },
  },
  {
    id: '32',
    title: 'The Labyrinth of Whispers',
    authors: [{ name: 'Katarina Volkov', bio: 'Katarina Volkov writes intricate psychological thrillers.' }],
    publisher: { name: 'Black Cat Books', location: 'Prague' },
    publicationDate: '2023-10-31',
    isbn: '978-1-9821-8881-7',
    genres: ['Mystery', 'Thriller'],
    tags: ['psychological', 'unreliable narrator', 'suspense'],
    description: 'A woman suffering from amnesia after a traumatic accident begins to suspect her loving husband is not who he says he is. The truth is locked in her fragmented memories.',
    language: 'English',
    format: 'Paperback',
    pages: 336,
    coverImgUrl: 'cover-art/mystery.png',
    price: 17.00,
    stock: 170,
    averageRating: 4.4,
    reviews: [
        { username: 'ThrillerFan', rating: 5, comment: 'Twisty, dark, and utterly compelling. I did not see that ending coming!', timestamp: '2023-11-15T21:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 0.9 },
  },
  {
    id: '33',
    title: 'The Sword of the Seventh Sun',
    authors: [{ name: 'Gideon Drake', bio: 'Gideon Drake writes epic fantasy for a new generation.' }],
    publisher: { name: 'Wyrmwood Press', location: 'Edinburgh' },
    publicationDate: '2024-06-18',
    isbn: '978-0-7653-8970-2',
    genres: ['Fantasy', 'RPG-Lit'],
    tags: ['magic sword', 'epic quest', 'demons'],
    description: 'The quest for the Dragon\'s Tooth was only the beginning. Now, the heroes must reforge a legendary blade of light to banish a demon lord from the mortal realm.',
    language: 'English',
    format: 'Paperback',
    pages: 656,
    coverImgUrl: 'cover-art/rpg-lit.png',
    price: 20.99,
    stock: 220,
    averageRating: 0,
    reviews: [],
    series: { name: 'The Artifacts of Power', number: 2 },
    dimensions: { height: 8.5, width: 5.5, depth: 1.6 },
  },
  {
    id: '34',
    title: 'The Unseen Architect',
    authors: [{ name: 'Dr. Julian Finch', bio: 'Dr. Julian Finch is a philosopher of science and ethics.' }],
    publisher: { name: 'Academia Press', location: 'Oxford' },
    publicationDate: '2022-09-13',
    isbn: '978-0-19-886341-9',
    genres: ['Philosophy'],
    tags: ['ethics', 'technology', 'AI', 'future'],
    description: 'A thought-provoking exploration of the ethical dilemmas posed by artificial intelligence and the profound impact it will have on the future of humanity.',
    language: 'English',
    format: 'Hardcover',
    pages: 320,
    coverImgUrl: 'cover-art/philosophy.png',
    price: 30.00,
    stock: 80,
    averageRating: 4.7,
    reviews: [
        { username: 'Thinker', rating: 5, comment: 'A crucial and timely book. Finch tackles complex issues with clarity and nuance.', timestamp: '2022-10-01T12:00:00Z' },
    ],
    dimensions: { height: 9.2, width: 6.1, depth: 1.2 },
  },
  {
    id: '35',
    title: 'The Courage to Begin',
    authors: [{ name: 'Maya Rivera', bio: 'Maya Rivera is a life coach and motivational speaker.' }],
    publisher: { name: 'Ascend Media', location: 'Los Angeles' },
    publicationDate: '2023-05-09',
    isbn: '978-1-64250-899-5',
    genres: ['Self-Help'],
    tags: ['motivation', 'self-improvement', 'career', 'confidence'],
    description: 'A step-by-step guide to overcoming fear, silencing your inner critic, and taking the first bold steps toward the life you\'ve always dreamed of.',
    language: 'English',
    format: 'Paperback',
    pages: 256,
    coverImgUrl: 'cover-art/self-help.png',
    price: 17.95,
    stock: 300,
    averageRating: 4.8,
    reviews: [
        { username: 'GoGetter', rating: 5, comment: 'The kick in the pants I needed! Practical, inspiring, and full of actionable advice.', timestamp: '2023-05-25T14:00:00Z' },
    ],
    dimensions: { height: 8.5, width: 5.5, depth: 0.7 },
  },
  {
    id: '36',
    title: 'The City of a Thousand Stars',
    authors: [{ name: 'Jax Orion', bio: 'Jax Orion is a visionary sci-fi author.' }],
    publisher: { name: 'Nebula Press', location: 'San Francisco' },
    publicationDate: '2025-01-14',
    isbn: '978-1-9821-3752-5',
    genres: ['Science Fiction'],
    tags: ['space opera', 'alien civilizations', 'discovery'],
    description: 'The stunning conclusion to The Starlight Chronicles. The crew of the Stardust reaches a legendary city, home to a thousand alien species, only to find it on the brink of a civil war that could unravel the galaxy.',
    language: 'English',
    format: 'Paperback',
    pages: 580,
    coverImgUrl: 'cover-art/science-fiction.png',
    price: 20.99,
    stock: 300,
    averageRating: 0,
    reviews: [],
    series: { name: 'The Starlight Chronicles', number: 3 },
    dimensions: { height: 8.2, width: 5.5, depth: 1.4 },
  },
  {
    id: '37',
    title: 'The Baker of Willow Creek',
    authors: [{ name: 'Penelope Plum', bio: 'Penelope Plum writes cozy, heartwarming stories.' }],
    publisher: { name: 'Evergreen Romance', location: 'Charleston' },
    publicationDate: '2023-03-07',
    isbn: '978-0-593-33530-4',
    genres: ['Romance'],
    tags: ['small town', 'baking', 'contemporary romance'],
    description: 'A big-city pastry chef, recovering from a career-ending burnout, finds a new recipe for life and love when she takes over her grandmother\'s small-town bakery.',
    language: 'English',
    format: 'Paperback',
    pages: 320,
    coverImgUrl: 'cover-art/romance.png',
    price: 16.00,
    stock: 210,
    averageRating: 4.5,
    reviews: [
        { username: 'CozyReader', rating: 5, comment: 'The sweetest book I\'ve read all year. Pure comfort.', timestamp: '2023-03-20T16:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 0.8 },
  },
  {
    id: '38',
    title: 'The Shadow of the Colossus',
    authors: [{ name: 'Adrian Valerius', bio: 'Adrian Valerius is an archaeologist and historian.' }],
    publisher: { name: 'Antiquarian Press', location: 'Rome' },
    publicationDate: '2024-03-10',
    isbn: '978-0-525-53973-6',
    genres: ['Mystery', 'Biography'],
    tags: ['archaeology', 'ancient greece', 'historical mystery'],
    description: 'The archaeologist from Echoes of the Forgotten travels to Greece to investigate the mysterious disappearance of a colleague, a search that leads him to a lost wonder of the ancient world.',
    language: 'English',
    format: 'Hardcover',
    pages: 448,
    coverImgUrl: 'cover-art/biography.png',
    price: 30.99,
    stock: 85,
    averageRating: 0,
    reviews: [],
    series: { name: 'The Artifact Hunter', number: 2 },
    dimensions: { height: 9.5, width: 6.4, depth: 1.6 },
  },
  {
    id: '39',
    title: 'The Boy Who Built a Rocket',
    authors: [{ name: 'Leo Stellar', bio: 'Leo Stellar writes inspiring stories for ambitious kids.' }],
    publisher: { name: 'Little Sprouts Books', location: 'Asheville' },
    publicationDate: '2024-05-14',
    isbn: '978-1-5344-9928-3',
    genres: ['Childrens'],
    tags: ['space', 'invention', 'dreams', 'science'],
    description: 'A young boy, inspired by the stars, decides to build a rocket in his backyard. With the help of his friends and a little bit of imagination, he reaches for the moon.',
    language: 'English',
    format: 'Hardcover',
    pages: 40,
    coverImgUrl: 'cover-art/childrens.png',
    price: 18.99,
    stock: 180,
    averageRating: 0,
    reviews: [],
    dimensions: { height: 10.0, width: 8.0, depth: 0.6 },
  },
  {
    id: '40',
    title: 'The Crown of Whispers',
    authors: [{ name: 'Lyra Meadowlight', bio: 'Lyra Meadowlight writes enchanting fantasy tales.' }],
    publisher: { name: 'Fable & Fern', location: 'Portland' },
    publicationDate: '2026-01-15',
    isbn: '978-0-7653-7650-4',
    genres: ['Fantasy'],
    tags: ['magic', 'royalty', 'adventure'],
    description: 'The epic conclusion to The Forest Chronicles. The rightful heir must claim a magical crown to unite the kingdoms of humans and fae against a common enemy.',
    language: 'English',
    format: 'Hardcover',
    pages: 410,
    coverImgUrl: 'cover-art/fantasy.png',
    price: 28.99,
    stock: 150,
    averageRating: 0,
    reviews: [],
    series: { name: 'The Forest Chronicles', number: 3 },
    dimensions: { height: 9.0, width: 6.0, depth: 1.5 },
  },
  {
    id: '41',
    title: 'The Silk Weaver\'s Daughter',
    authors: [{ name: 'Mei Lin', bio: 'Mei Lin writes captivating historical fiction.' }],
    publisher: { name: 'Dragonfly Press', location: 'Shanghai' },
    publicationDate: '2023-02-21',
    isbn: '978-0-7582-9473-1',
    genres: ['Biography'],
    tags: ['historical fiction', 'china', 'family saga'],
    description: 'A multi-generational saga that follows a family of silk weavers in early 20th-century China, as they navigate war, revolution, and the changing tides of history.',
    language: 'English',
    format: 'Paperback',
    pages: 480,
    coverImgUrl: 'cover-art/biography.png',
    price: 17.99,
    stock: 130,
    averageRating: 4.6,
    reviews: [
        { username: 'HistFicFan', rating: 5, comment: 'A beautiful, sweeping story. I was completely immersed.', timestamp: '2023-03-10T14:00:00Z' },
    ],
    dimensions: { height: 8.2, width: 5.5, depth: 1.2 },
  },
  {
    id: '42',
    title: 'The Last Sunset',
    authors: [{ name: 'Kai Moreno', bio: 'Kai Moreno writes poignant and thought-provoking travelogues.' }],
    publisher: { name: 'Odyssey Books', location: 'Dublin' },
    publicationDate: '2024-04-16',
    isbn: '978-1-64049-425-9',
    genres: ['Travel'],
    tags: ['memoir', 'south america', 'self-discovery'],
    description: 'A journey to the end of the world. A writer travels to Patagonia to confront a past tragedy and finds unexpected healing in the raw, untamed beauty of the landscape.',
    language: 'English',
    format: 'Paperback',
    pages: 288,
    coverImgUrl: 'cover-art/travel.png',
    price: 16.99,
    stock: 110,
    averageRating: 0,
    reviews: [],
    dimensions: { height: 8.0, width: 5.2, depth: 0.8 },
  },
  {
    id: '43',
    title: 'The Perfect Loaf: A Guide for Artisan Bakers',
    authors: [{ name: 'Julian Armstrong', bio: 'Julian Armstrong is a master baker and founder of a renowned bakery.' }],
    publisher: { name: 'Gourmand Press', location: 'Florence' },
    publicationDate: '2021-09-07',
    isbn: '978-0-399-58205-0',
    genres: ['Cooking'],
    tags: ['baking', 'sourdough', 'cookbook', 'technique'],
    description: 'The definitive guide to baking artisan bread at home. From starters to shaping, this book covers every detail with clear instructions and beautiful photography.',
    language: 'English',
    format: 'Hardcover',
    pages: 400,
    coverImgUrl: 'cover-art/cooking.png',
    price: 40.00,
    stock: 150,
    averageRating: 4.9,
    reviews: [
        { username: 'HomeBaker', rating: 5, comment: 'My bread has never been better. This book is a game-changer.', timestamp: '2021-10-01T11:00:00Z' },
        { username: 'SourdoughSam', rating: 5, comment: 'An indispensable resource for any serious baker.', timestamp: '2021-10-15T17:00:00Z' },
    ],
    dimensions: { height: 10.8, width: 8.8, depth: 1.4 },
  },
  {
    id: '44',
    title: 'The Serpent\'s Kiss',
    authors: [{ name: 'Isolde Nightshade', bio: 'Isolde Nightshade pens gothic romances with a dark twist.' }],
    publisher: { name: 'Gallows Press', location: 'New Orleans' },
    publicationDate: '2022-10-25',
    isbn: '978-0-593-31045-5',
    genres: ['Mystery', 'Romance'],
    tags: ['gothic romance', 'vampires', 'forbidden love'],
    description: 'A young governess in a remote, crumbling manor finds herself drawn to its enigmatic and brooding master, who harbors a centuries-old secret.',
    language: 'English',
    format: 'Paperback',
    pages: 400,
    coverImgUrl: 'cover-art/romance.png',
    price: 16.99,
    stock: 190,
    averageRating: 4.3,
    reviews: [
        { username: 'GothRomanceReader', rating: 4, comment: 'Dark, dangerous, and deeply romantic. A perfect gothic read.', timestamp: '2022-11-10T20:00:00Z' },
    ],
    dimensions: { height: 8.2, width: 5.5, depth: 1.1 },
  },
  {
    id: '45',
    title: 'The Code of Life',
    authors: [{ name: 'Dr. Evelyn Reed', bio: 'Dr. Evelyn Reed is a theoretical physicist and science communicator.' }],
    publisher: { name: 'Helix Books', location: 'Cambridge' },
    publicationDate: '2024-10-01',
    isbn: '978-0-593-23746-9',
    genres: ['Science Fiction'],
    tags: ['hard sci-fi', 'genetics', 'bio-thriller'],
    description: 'A brilliant geneticist discovers a hidden code within human DNA, a message from an ancient, unknown intelligence. But decoding it could unleash a power that humanity is not ready to control.',
    language: 'English',
    format: 'Hardcover',
    pages: 480,
    coverImgUrl: 'cover-art/science-fiction.png',
    price: 29.00,
    stock: 100,
    averageRating: 0,
    reviews: [],
    dimensions: { height: 9.3, width: 6.3, depth: 1.7 },
  },
  {
    id: '46',
    title: 'The Starfall Knight',
    authors: [{ name: 'Astrid Valerius', bio: 'Astrid Valerius writes YA fantasy with a cosmic twist.' }],
    publisher: { name: 'Moonbeam Books', location: 'London' },
    publicationDate: '2022-06-14',
    isbn: '978-1-4088-5570-6',
    genres: ['Young Adult', 'Fantasy'],
    tags: ['knights', 'magic', 'celestial', 'romance'],
    description: 'A girl who dreams of becoming a knight gets her chance when a fallen star grants her a suit of celestial armor. But the armor comes with a destiny she may not be ready to accept.',
    language: 'English',
    format: 'Paperback',
    pages: 416,
    coverImgUrl: 'cover-art/young-adult.png',
    price: 14.99,
    stock: 160,
    averageRating: 4.6,
    reviews: [
        { username: 'YA_Knight', rating: 5, comment: 'Loved this! A fresh take on the knight trope with a fantastic magic system.', timestamp: '2022-07-01T13:00:00Z' },
    ],
    dimensions: { height: 7.8, width: 5.1, depth: 1.2 },
  },
  {
    id: '47',
    title: 'The Oracle of Delphi',
    authors: [{ name: 'Helena Troy', bio: 'Helena Troy is a classicist and historical novelist.' }],
    publisher: { name: 'Antiquarian Press', location: 'Rome' },
    publicationDate: '2021-08-10',
    isbn: '978-0-525-53969-9',
    genres: ['Biography'],
    tags: ['ancient greece', 'mythology', 'historical fiction'],
    description: 'The story of the most powerful woman in ancient Greece, the Pythia, whose prophecies shaped the course of empires. A tale of power, politics, and divine inspiration.',
    language: 'English',
    format: 'Hardcover',
    pages: 400,
    coverImgUrl: 'cover-art/biography.png',
    price: 28.99,
    stock: 90,
    averageRating: 4.7,
    reviews: [
        { username: 'MythLover', rating: 5, comment: 'A stunning portrayal of the ancient world. Troy makes history feel alive.', timestamp: '2021-08-25T16:00:00Z' },
    ],
    dimensions: { height: 9.5, width: 6.4, depth: 1.4 },
  },
  {
    id: '48',
    title: 'The Golem of the Golden City',
    authors: [{ name: 'Gideon Drake', bio: 'Gideon Drake writes epic fantasy for a new generation.' }],
    publisher: { name: 'Wyrmwood Press', location: 'Edinburgh' },
    publicationDate: '2025-06-17',
    isbn: '978-0-7653-8972-6',
    genres: ['Fantasy', 'RPG-Lit'],
    tags: ['golems', 'magic city', 'epic fantasy'],
    description: 'The heroes must travel to a legendary city of inventors to stop a rogue artificer from unleashing an army of unstoppable golems upon the world.',
    language: 'English',
    format: 'Paperback',
    pages: 640,
    coverImgUrl: 'cover-art/rpg-lit.png',
    price: 21.99,
    stock: 230,
    averageRating: 0,
    reviews: [],
    series: { name: 'The Artifacts of Power', number: 3 },
    dimensions: { height: 8.5, width: 5.5, depth: 1.6 },
  },
  {
    id: '49',
    title: 'The Logic of Everything',
    authors: [{ name: 'Dr. Alistair Finch', bio: 'Dr. Alistair Finch is a logician and philosopher.' }],
    publisher: { name: 'Academia Press', location: 'Oxford' },
    publicationDate: '2023-09-12',
    isbn: '978-0-19-886343-3',
    genres: ['Philosophy'],
    tags: ['logic', 'reason', 'metaphysics', 'science'],
    description: 'An accessible yet profound journey into the principles of logic and reason, showing how they form the bedrock of science, mathematics, and our very understanding of reality.',
    language: 'English',
    format: 'Hardcover',
    pages: 288,
    coverImgUrl: 'cover-art/philosophy.png',
    price: 28.00,
    stock: 75,
    averageRating: 4.6,
    reviews: [
        { username: 'RationalMind', rating: 5, comment: 'A brilliant book that makes complex ideas understandable. Highly recommended.', timestamp: '2023-10-02T11:00:00Z' },
    ],
    dimensions: { height: 9.2, width: 6.1, depth: 1.1 },
  },
  {
    id: '50',
    title: 'The Path of Least Resistance',
    authors: [{ name: 'Brenda Croft', bio: 'Brenda Croft is an expert in productivity and personal development.' }],
    publisher: { name: 'Ascend Media', location: 'Los Angeles' },
    publicationDate: '2022-02-08',
    isbn: '978-1-64250-901-5',
    genres: ['Self-Help'],
    tags: ['productivity', 'habits', 'psychology', 'minimalism'],
    description: 'Stop fighting against yourself. This book reveals how to design your environment and build systems to make good habits effortless and bad habits impossible.',
    language: 'English',
    format: 'Paperback',
    pages: 240,
    coverImgUrl: 'cover-art/self-help.png',
    price: 16.95,
    stock: 350,
    averageRating: 4.9,
    reviews: [
        { username: 'ProductivePro', rating: 5, comment: 'A revolutionary approach to habit formation. This book has changed the way I work and live.', timestamp: '2022-02-25T09:00:00Z' },
        { username: 'LifeHack', rating: 5, comment: 'Simple, powerful, and effective. A must-read.', timestamp: '2022-03-10T18:00:00Z' },
    ],
    dimensions: { height: 8.5, width: 5.5, depth: 0.6 },
  },
  {
    id: '51',
    title: 'The Ghost of Blackwood Manor',
    authors: [{ name: 'Eleanora Black', bio: 'Eleanora Black writes chilling ghost stories.' }],
    publisher: { name: 'Gallows Press', location: 'New Orleans' },
    publicationDate: '2024-09-10',
    isbn: '978-0-593-31047-9',
    genres: ['Mystery', 'Thriller'],
    tags: ['haunted house', 'gothic', 'supernatural'],
    description: 'A skeptical paranormal investigator is hired to debunk the haunting of a remote English manor, only to find the ghost is very real and has a dark secret to protect.',
    language: 'English',
    format: 'Paperback',
    pages: 352,
    coverImgUrl: 'cover-art/mystery.png',
    price: 18.99,
    stock: 150,
    averageRating: 0,
    reviews: [],
    dimensions: { height: 8.2, width: 5.5, depth: 0.9 },
  },
  {
    id: '52',
    title: 'The City of Shifting Sands',
    authors: [{ name: 'Amara Zahir', bio: 'Amara Zahir weaves tales inspired by Middle Eastern folklore.' }],
    publisher: { name: 'Ink & Compass', location: 'Dublin' },
    publicationDate: '2023-07-18',
    isbn: '978-1-5247-6203-7',
    genres: ['Fantasy'],
    tags: ['mythology', 'djinn', 'desert', 'adventure'],
    description: 'In a mythical desert kingdom, a young thief steals a cursed lamp, unleashing a powerful djinn who offers three wishes that will change the fate of her city forever.',
    language: 'English',
    format: 'Hardcover',
    pages: 384,
    coverImgUrl: 'cover-art/fantasy.png',
    price: 26.99,
    stock: 120,
    averageRating: 4.7,
    reviews: [
        { username: 'MythReader', rating: 5, comment: 'A vibrant and magical tale. I was swept away to another world.', timestamp: '2023-08-02T17:00:00Z' },
    ],
    dimensions: { height: 8.8, width: 5.9, depth: 1.4 },
  },
  {
    id: '53',
    title: 'The Andromeda Strain 2.0',
    authors: [{ name: 'Dr. Kenji Tanaka', bio: 'Dr. Kenji Tanaka is a microbiologist and author.' }],
    publisher: { name: 'Orbital Publishing', location: 'Houston' },
    publicationDate: '2022-11-08',
    isbn: '978-0-593-44114-2',
    genres: ['Science Fiction', 'Thriller'],
    tags: ['bio-thriller', 'pandemic', 'science'],
    description: 'A deadly, extraterrestrial microbe is discovered in a meteorite. A team of scientists must race against time to understand and contain it before it triggers a global pandemic.',
    language: 'English',
    format: 'Paperback',
    pages: 432,
    coverImgUrl: 'cover-art/science-fiction.png',
    price: 18.00,
    stock: 180,
    averageRating: 4.4,
    reviews: [
        { username: 'BioNerd', rating: 5, comment: 'A terrifyingly plausible and scientifically grounded thriller.', timestamp: '2022-11-25T12:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 1.2 },
  },
  {
    id: '54',
    title: 'The Last Queen',
    authors: [{ name: 'Dr. Cleopatra Jones', bio: 'Dr. Cleopatra Jones is an Egyptologist and historian.' }],
    publisher: { name: 'Antiquarian Press', location: 'Rome' },
    publicationDate: '2023-08-08',
    isbn: '978-0-525-53975-0',
    genres: ['Biography'],
    tags: ['cleopatra', 'ancient egypt', 'history', 'rome'],
    description: 'A definitive and intimate biography of Cleopatra, the last pharaoh of Egypt. Separating myth from reality, it reveals a brilliant strategist and ruthless politician.',
    language: 'English',
    format: 'Hardcover',
    pages: 544,
    coverImgUrl: 'cover-art/biography.png',
    price: 35.00,
    stock: 80,
    averageRating: 4.8,
    reviews: [
        { username: 'EgyptFan', rating: 5, comment: 'The best biography of Cleopatra I have ever read. Meticulously researched and utterly captivating.', timestamp: '2023-08-22T15:00:00Z' },
    ],
    dimensions: { height: 9.6, width: 6.5, depth: 1.9 },
  },
  {
    id: '55',
    title: 'The Dragon Who Couldn\'t Fly',
    authors: [{ name: 'Sparky Brightscale', bio: 'Sparky Brightscale is a dragon who loves to tell stories.' }],
    publisher: { name: 'Little Sprouts Books', location: 'Asheville' },
    publicationDate: '2022-10-11',
    isbn: '978-1-5344-9930-6',
    genres: ['Childrens'],
    tags: ['dragons', 'courage', 'friendship', 'acceptance'],
    description: 'A young dragon is born without the ability to fly. With the help of his woodland friends, he learns that his true strength lies in his kind heart and clever mind.',
    language: 'English',
    format: 'Hardcover',
    pages: 36,
    coverImgUrl: 'cover-art/childrens.png',
    price: 17.99,
    stock: 220,
    averageRating: 4.9,
    reviews: [
        { username: 'DadReads', rating: 5, comment: 'A wonderful story about embracing what makes you unique. My son adores it.', timestamp: '2022-10-25T19:00:00Z' },
    ],
    dimensions: { height: 9.5, width: 9.5, depth: 0.5 },
  },
  {
    id: '56',
    title: 'The Damascus Protocol',
    authors: [{ name: 'Zahara Al-Jamil', bio: 'Zahara Al-Jamil is an expert in Middle Eastern affairs.' }],
    publisher: { name: 'Capitol Books', location: 'Washington D.C.' },
    publicationDate: '2022-05-10',
    isbn: '978-1-5011-7138-2',
    genres: ['Political Thriller'],
    tags: ['espionage', 'middle east', 'spy', 'suspense'],
    description: 'A CIA case officer in Damascus is on the run after her cover is blown while trying to exfiltrate a high-level Syrian general. She must rely on her wits to survive and expose the mole in the agency.',
    language: 'English',
    format: 'Paperback',
    pages: 432,
    coverImgUrl: 'cover-art/political-thriller.png',
    price: 17.99,
    stock: 160,
    averageRating: 4.5,
    reviews: [
        { username: 'SpyNovelFan', rating: 5, comment: 'A tense, authentic, and intelligent spy thriller. One of the best I\'ve read in years.', timestamp: '2022-05-25T11:00:00Z' },
    ],
    dimensions: { height: 8.5, width: 5.5, depth: 1.1 },
  },
  {
    id: '57',
    title: 'The Lighthouse Keeper\'s Love',
    authors: [{ name: 'Charlotte Finch', bio: 'Charlotte Finch writes historical romance with a touch of melancholy.' }],
    publisher: { name: 'Evergreen Romance', location: 'Charleston' },
    publicationDate: '2021-08-24',
    isbn: '978-0-593-33527-4',
    genres: ['Romance'],
    tags: ['historical romance', 'wartime', 'letters', 'love story'],
    description: 'During World War II, a lonely lighthouse keeper on the coast of Maine begins a correspondence with a soldier on the front lines. Their letters build a powerful bond that must endure the tests of war and time.',
    language: 'English',
    format: 'Paperback',
    pages: 368,
    coverImgUrl: 'cover-art/romance.png',
    price: 16.00,
    stock: 200,
    averageRating: 4.7,
    reviews: [
        { username: 'HistoricalRomanceLover', rating: 5, comment: 'A beautiful, heartbreaking, and ultimately hopeful love story. I cried my eyes out.', timestamp: '2021-09-10T14:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 1.0 },
  },
  {
    id: '58',
    title: 'The Road to Marrakesh',
    authors: [{ name: 'Sofia Benali', bio: 'Sofia Benali is a travel writer with a passion for North Africa.' }],
    publisher: { name: 'Odyssey Books', location: 'Dublin' },
    publicationDate: '2022-03-15',
    isbn: '978-1-64049-427-3',
    genres: ['Travel'],
    tags: ['morocco', 'memoir', 'culture', 'food'],
    description: 'A vibrant and sensory journey through the souks, cities, and deserts of Morocco. A celebration of the country\'s rich culture, history, and culinary traditions.',
    language: 'English',
    format: 'Paperback',
    pages: 304,
    coverImgUrl: 'cover-art/travel.png',
    price: 17.99,
    stock: 150,
    averageRating: 4.6,
    reviews: [
        { username: 'TravelBug', rating: 5, comment: 'Made me feel like I was there. Beautifully written and full of fascinating insights.', timestamp: '2022-04-01T10:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 0.8 },
  },
  {
    id: '59',
    title: 'The City of Lost Dreams',
    authors: [{ name: 'Silas North', bio: 'Silas North writes dystopian fiction for young adults.' }],
    publisher: { name: 'Moonbeam Books', location: 'London' },
    publicationDate: '2023-10-17',
    isbn: '978-1-4088-5572-0',
    genres: ['Young Adult', 'Science Fiction'],
    tags: ['dystopian', 'rebellion', 'technology'],
    description: 'In a futuristic city where emotions are suppressed by technology, a teenage girl begins to experience feelings for the first time. Her newfound emotions make her a threat to the system and a beacon of hope for a rebellion.',
    language: 'English',
    format: 'Paperback',
    pages: 368,
    coverImgUrl: 'cover-art/young-adult.png',
    price: 15.99,
    stock: 190,
    averageRating: 4.5,
    reviews: [
        { username: 'DystopianFan', rating: 5, comment: 'A compelling and thought-provoking read. A great new voice in YA.', timestamp: '2023-11-01T16:00:00Z' },
    ],
    dimensions: { height: 7.8, width: 5.1, depth: 1.0 },
  },
  {
    id: '60',
    title: 'The Fermented Feast',
    authors: [{ name: 'Eva Petrov', bio: 'Eva Petrov is a chef and expert in fermentation.' }],
    publisher: { name: 'Gourmand Press', location: 'Florence' },
    publicationDate: '2023-06-06',
    isbn: '978-0-399-58207-4',
    genres: ['Cooking'],
    tags: ['fermentation', 'cookbook', 'healthy eating', 'probiotics'],
    description: 'Unlock the power of fermentation with over 100 recipes for everything from kimchi and kombucha to sourdough and sauerkraut. A guide to creating delicious, probiotic-rich foods in your own kitchen.',
    language: 'English',
    format: 'Hardcover',
    pages: 320,
    coverImgUrl: 'cover-art/cooking.png',
    price: 32.50,
    stock: 100,
    averageRating: 4.9,
    reviews: [
        { username: 'HealthyChef', rating: 5, comment: 'An amazing resource for anyone interested in fermentation. The recipes are clear and delicious.', timestamp: '2023-06-20T13:00:00Z' },
    ],
    dimensions: { height: 10.2, width: 8.3, depth: 1.1 },
  },
  {
    id: '61',
    title: 'The Blackout Protocol',
    authors: [{ name: 'Colonel Rex "Havoc" Stone', bio: 'Colonel Rex Stone is a decorated special forces veteran.' }],
    publisher: { name: 'Stealth Publishing', location: 'San Diego' },
    publicationDate: '2025-11-04',
    isbn: '978-0-399-59345-2',
    genres: ['Military Thriller'],
    tags: ['special forces', 'emp', 'action', 'survival'],
    description: 'An electromagnetic pulse attack plunges the United States into darkness. The Havoc team must navigate a chaotic, powerless landscape to hunt down the terrorists responsible and prevent a second, more devastating strike.',
    language: 'English',
    format: 'Paperback',
    pages: 416,
    coverImgUrl: 'cover-art/military-thriller.png',
    price: 18.99,
    stock: 250,
    averageRating: 0,
    reviews: [],
    series: { name: 'Havoc', number: 3 },
    dimensions: { height: 8.2, width: 5.5, depth: 1.1 },
  },
  {
    id: '62',
    title: 'The Silent Patient Wakes',
    authors: [{ name: 'Alex Michaelides', bio: 'Alex Michaelides is a bestselling author of psychological thrillers.' }],
    publisher: { name: 'Black Cat Books', location: 'Prague' },
    publicationDate: '2024-02-13',
    isbn: '978-1-9821-8883-1',
    genres: ['Mystery', 'Thriller'],
    tags: ['psychological', 'sequel', 'suspense'],
    description: 'Years after the shocking events of The Silent Patient, a new therapist at the Grove re-opens the case, convinced there is more to the story. But some secrets are meant to stay buried.',
    language: 'English',
    format: 'Paperback',
    pages: 352,
    coverImgUrl: 'cover-art/mystery.png',
    price: 18.00,
    stock: 200,
    averageRating: 0,
    reviews: [],
    dimensions: { height: 8.0, width: 5.2, depth: 0.9 },
  },
  {
    id: '63',
    title: 'The Necromancer\'s Gambit',
    authors: [{ name: 'Gideon Drake', bio: 'Gideon Drake writes epic fantasy for a new generation.' }],
    publisher: { name: 'Wyrmwood Press', location: 'Edinburgh' },
    publicationDate: '2026-06-16',
    isbn: '978-0-7653-8974-0',
    genres: ['Fantasy', 'RPG-Lit'],
    tags: ['necromancy', 'undead', 'epic fantasy'],
    description: 'The heroes face their greatest challenge yet when a powerful necromancer raises an army of the dead to conquer the living. The fate of the world rests on a desperate gambit.',
    language: 'English',
    format: 'Paperback',
    pages: 672,
    coverImgUrl: 'cover-art/rpg-lit.png',
    price: 22.99,
    stock: 240,
    averageRating: 0,
    reviews: [],
    series: { name: 'The Artifacts of Power', number: 4 },
    dimensions: { height: 8.5, width: 5.5, depth: 1.7 },
  },
  {
    id: '64',
    title: 'The Nature of Consciousness',
    authors: [{ name: 'Dr. Penelope Crane', bio: 'Dr. Penelope Crane is a neuroscientist and philosopher.' }],
    publisher: { name: 'Academia Press', location: 'Oxford' },
    publicationDate: '2021-10-12',
    isbn: '978-0-19-886345-7',
    genres: ['Philosophy', 'Science'],
    tags: ['consciousness', 'neuroscience', 'mind', 'philosophy of mind'],
    description: 'A groundbreaking and accessible exploration of one of science\'s greatest mysteries: the nature of consciousness. This book bridges the gap between neuroscience and philosophy.',
    language: 'English',
    format: 'Hardcover',
    pages: 336,
    coverImgUrl: 'cover-art/philosophy.png',
    price: 32.00,
    stock: 85,
    averageRating: 4.8,
    reviews: [
        { username: 'NeuroPhil', rating: 5, comment: 'A fascinating and important work. Crane makes a complex subject engaging and understandable.', timestamp: '2021-11-01T10:00:00Z' },
    ],
    dimensions: { height: 9.2, width: 6.1, depth: 1.2 },
  },
  {
    id: '65',
    title: 'The Uncluttered Home',
    authors: [{ name: 'Kenji Tanaka', bio: 'Kenji Tanaka is a minimalist and organizational consultant.' }],
    publisher: { name: 'Ascend Media', location: 'Los Angeles' },
    publicationDate: '2023-08-22',
    isbn: '978-1-64250-903-9',
    genres: ['Self-Help'],
    tags: ['minimalism', 'organization', 'home', 'lifestyle'],
    description: 'Discover the joy of living with less. This book offers a practical, room-by-room guide to decluttering your home and simplifying your life, inspired by Japanese principles of minimalism.',
    language: 'English',
    format: 'Paperback',
    pages: 224,
    coverImgUrl: 'cover-art/self-help.png',
    price: 18.95,
    stock: 320,
    averageRating: 4.9,
    reviews: [
        { username: 'MinimalistMom', rating: 5, comment: 'This book is a breath of fresh air. The advice is practical and the philosophy is inspiring.', timestamp: '2023-09-10T13:00:00Z' },
    ],
    dimensions: { height: 8.5, width: 5.5, depth: 0.6 },
  },
  {
    id: '66',
    title: 'The Void Dragon',
    authors: [{ name: 'Jax Orion', bio: 'Jax Orion is a visionary sci-fi author.' }],
    publisher: { name: 'Nebula Press', location: 'San Francisco' },
    publicationDate: '2026-01-13',
    isbn: '978-1-9821-3754-9',
    genres: ['Science Fiction', 'Fantasy'],
    tags: ['space fantasy', 'dragons', 'magic', 'new series'],
    description: 'A new epic from the author of The Starlight Chronicles. In a galaxy where magic and technology collide, a young pilot forms an unlikely bond with a mythical Void Dragon, a creature thought to be extinct.',
    language: 'English',
    format: 'Paperback',
    pages: 500,
    coverImgUrl: 'cover-art/science-fiction.png',
    price: 19.99,
    stock: 300,
    averageRating: 0,
    reviews: [],
    dimensions: { height: 8.2, width: 5.5, depth: 1.3 },
  },
  {
    id: '67',
    title: 'The Last Dance',
    authors: [{ name: 'Camila Garcia', bio: 'Camila Garcia writes passionate and dramatic love stories.' }],
    publisher: { name: 'Evergreen Romance', location: 'Charleston' },
    publicationDate: '2022-09-20',
    isbn: '978-0-593-33532-8',
    genres: ['Romance'],
    tags: ['dance', 'rivals to lovers', 'contemporary romance'],
    description: 'Two rival ballerinas, competing for the lead role in a prestigious production, find their professional animosity turning into an unexpected and forbidden passion.',
    language: 'English',
    format: 'Paperback',
    pages: 336,
    coverImgUrl: 'cover-art/romance.png',
    price: 16.00,
    stock: 170,
    averageRating: 4.4,
    reviews: [
        { username: 'DanceLover', rating: 4, comment: 'A dramatic and passionate story. The dance scenes were beautifully written.', timestamp: '2022-10-05T18:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 0.9 },
  },
  {
    id: '68',
    title: 'The Lost Library of Alexandria',
    authors: [{ name: 'Dr. Marcus Aurelius', bio: 'Dr. Marcus Aurelius is a historian of the ancient world.' }],
    publisher: { name: 'Antiquarian Press', location: 'Rome' },
    publicationDate: '2022-06-07',
    isbn: '978-0-525-53977-4',
    genres: ['Biography'],
    tags: ['history', 'alexandria', 'library', 'ancient world'],
    description: 'The definitive history of the most famous library in the ancient world. This book explores its rise, its tragic fall, and the priceless knowledge that was lost to history.',
    language: 'English',
    format: 'Hardcover',
    pages: 480,
    coverImgUrl: 'cover-art/biography.png',
    price: 32.99,
    stock: 95,
    averageRating: 4.9,
    reviews: [
        { username: 'HistoryMajor', rating: 5, comment: 'A fascinating and heartbreaking account of a monumental loss. A must-read for any history lover.', timestamp: '2022-06-25T10:00:00Z' },
    ],
    dimensions: { height: 9.5, width: 6.4, depth: 1.7 },
  },
  {
    id: '69',
    title: 'The Magical Treehouse',
    authors: [{ name: 'Lily Pad', bio: 'Lily Pad writes whimsical adventures for children.' }],
    publisher: { name: 'Little Sprouts Books', location: 'Asheville' },
    publicationDate: '2021-04-20',
    isbn: '978-1-5344-9932-0',
    genres: ['Childrens'],
    tags: ['magic', 'adventure', 'treehouse', 'imagination'],
    description: 'Two siblings discover a magical treehouse in their backyard that can travel to any place they can imagine. Their first adventure takes them to a land of friendly dinosaurs.',
    language: 'English',
    format: 'Hardcover',
    pages: 48,
    coverImgUrl: 'cover-art/childrens.png',
    price: 18.99,
    stock: 250,
    averageRating: 4.8,
    reviews: [
        { username: 'ReadingParent', rating: 5, comment: 'A wonderful start to a new series. My kids are already asking for the next book!', timestamp: '2021-05-05T19:00:00Z' },
    ],
    series: { name: 'The Magical Treehouse Adventures', number: 1 },
    dimensions: { height: 10.0, width: 8.0, depth: 0.6 },
  },
  {
    id: '70',
    title: 'The Serpent in the Garden',
    authors: [{ name: 'Lord Ashworth', bio: 'Lord Ashworth is a master of the classic English mystery.' }],
    publisher: { name: 'Black Cat Books', location: 'Prague' },
    publicationDate: '2023-05-16',
    isbn: '978-1-9821-8885-5',
    genres: ['Mystery'],
    tags: ['cozy mystery', 'english countryside', 'gardening'],
    description: 'A quiet English village is rocked by murder when a controversial garden show judge is found dead, poisoned by a rare flower. A retired detective must put his pruning shears aside to solve the case.',
    language: 'English',
    format: 'Paperback',
    pages: 304,
    coverImgUrl: 'cover-art/mystery.png',
    price: 16.00,
    stock: 180,
    averageRating: 4.3,
    reviews: [
        { username: 'CozyFan', rating: 4, comment: 'A charming and clever mystery. Perfect for a rainy day.', timestamp: '2023-06-01T15:00:00Z' },
    ],
    dimensions: { height: 8.0, width: 5.2, depth: 0.8 },
  }
];
