/*!
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */
/*!
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */

export interface Host {
  name: string;
  avatarUrl: string;
  joinDate: string;
  isSuperhost: boolean;
}

export interface Amenity {
  name: string;
  icon: string;
}

export interface Rule {
  text: string;
  allowed: boolean;
}

export interface Policy {
  title: string;
  content: string;
}

export interface ReviewAuthor {
    name: string;
    avatarUrl: string;
}

export interface Review {
  author: ReviewAuthor;
  date: string;
  rating: number;
  text: string;
}

export interface ListingImage {
  url: string;
  alt: string;
}

export interface Listing {
  id: string;
  title: string;
  location: string;
  pricePerNight: number;
  rating: number;
  reviewCount: number;
  guests: number;
  bedrooms: number;
  beds: number;
  baths: number;
  description: string;
  host: Host;
  amenities: Amenity[];
  rules: Rule[];
  policies: Policy[];
  reviews: Review[];
  coverImg: ListingImage;
  imgs: ListingImage[];
}

export const DATA: Listing[] = [
  {
    id: '1',
    title: 'Cozy Mountain Cabin',
    location: 'Aspen, Colorado',
    pricePerNight: 250,
    rating: 4.8,
    reviewCount: 120,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    description: 'Escape to our charming cabin nestled in the heart of the Rocky Mountains. Perfect for a romantic getaway or a small family vacation, this cozy retreat offers breathtaking views, a warm fireplace, and easy access to world-class skiing and hiking trails. The interior is thoughtfully decorated with rustic charm and modern amenities to ensure a comfortable stay.',
    host: {
      name: 'John & Jane Smith',
      avatarUrl: 'properties/mountain-cabin.png',
      joinDate: '2018-05-12',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'TV', icon: 'tv' },
      { name: 'Iron', icon: 'iron' },
      { name: 'Hair dryer', icon: 'dryer' },
      { name: 'Washer', icon: 'local_laundry_service' },
      { name: 'Dryer', icon: 'local_laundry_service' },
      { name: 'Hot water', icon: 'hot_tub' },
      { name: 'Fireplace', icon: 'fireplace' },
      { name: 'Private entrance', icon: 'meeting_room' },
      { name: 'Shampoo', icon: 'wash' },
      { name: 'Conditioner', icon: 'wash' },
      { name: 'Shower gel', icon: 'wash' },
      { name: 'Bed linens', icon: 'bed' },
      { name: 'Extra pillows and blankets', icon: 'bed' },
      { name: 'Hangers', icon: 'hanger' },
      { name: 'Smoke alarm', icon: 'smoke_free' },
      { name: 'Carbon monoxide alarm', icon: 'smoke_free' },
      { name: 'First aid kit', icon: 'medical_services' },
      { name: 'Fire extinguisher', icon: 'fire_extinguisher' },
      { name: 'Dishes and silverware', icon: 'restaurant' },
      { name: 'Cooking basics', icon: 'soup_kitchen' },
      { name: 'Oven', icon: 'oven' },
      { name: 'Stove', icon: 'stove' },
      { name: 'Refrigerator', icon: 'kitchen' },
      { name: 'Dishwasher', icon: 'dishwasher' },
      { name: 'Coffee maker', icon: 'coffee_maker' },
      { name: 'Microwave', icon: 'microwave' },
      { name: 'Toaster', icon: 'toaster' },
      { name: 'Blender', icon: 'blender' },
      { name: 'Barbecue utensils', icon: 'outdoor_grill' },
      { name: 'Dining table', icon: 'restaurant' },
      { name: 'Patio or balcony', icon: 'balcony' },
      { name: 'Backyard', icon: 'yard' },
      { name: 'Outdoor furniture', icon: 'deck' },
      { name: 'BBQ grill', icon: 'outdoor_grill' },
      { name: 'Freezer', icon: 'ac_unit' },
      { name: 'Lake access', icon: 'waves' },
      { name: 'Mountain views', icon: 'terrain' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
      { text: 'No parties or events', allowed: false },
      { text: 'Check-in is anytime after 3 PM', allowed: true },
      { text: 'Check-out by 11 AM', allowed: true },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Free cancellation for 48 hours. After that, cancel up to 7 days before check-in and get a 50% refund, minus the service fee.' },
    ],
    reviews: [
      {
        author: { name: 'Alice', avatarUrl: 'properties/mountain-cabin.png' },
        date: '2023-10-15',
        rating: 5,
        text: 'This cabin was the perfect mountain getaway! The views were incredible, and the fireplace made it so cozy. We loved being so close to the ski slopes. Highly recommend!',
      },
      {
        author: { name: 'Bob', avatarUrl: 'properties/mountain-cabin-2.png' },
        date: '2023-09-28',
        rating: 4,
        text: 'A wonderful and peaceful retreat. The cabin was clean and well-equipped. The only downside was the spotty wifi, but it was nice to disconnect for a bit.',
      },
      {
        author: { name: 'Charlie', avatarUrl: 'properties/mountain-cabin-3.png' },
        date: '2023-08-12',
        rating: 5,
        text: 'We had an amazing time! The cabin is even more beautiful in person. The hosts were very responsive and provided great recommendations for local hikes.',
      },
    ],
    coverImg: {
      url: 'properties/mountain-cabin.png',
      alt: 'A cozy cabin in the mountains of Aspen, Colorado.',
    },
    imgs: [
      { url: 'properties/mountain-cabin.png', alt: 'The cabin exterior with a backdrop of snow-covered mountains.' },
      { url: 'properties/mountain-cabin-2.png', alt: 'The living room with a stone fireplace and comfortable seating.' },
      { url: 'properties/mountain-cabin-3.png', alt: 'The kitchen with modern appliances and rustic decor.' },
      { url: 'properties/mountain-cabin.png', alt: 'The bedroom with a queen-sized bed and a view of the forest.' },
    ],
  },
  {
    id: '2',
    title: 'Luxury Beachfront Villa',
    location: 'Bali, Indonesia',
    pricePerNight: 500,
    rating: 4.9,
    reviewCount: 250,
    guests: 8,
    bedrooms: 4,
    beds: 4,
    baths: 4,
    description: 'Indulge in the ultimate tropical escape at our luxurious beachfront villa in Bali. With a private infinity pool, direct beach access, and stunning ocean views from every room, this is the perfect setting for an unforgettable vacation. Our dedicated staff is on hand to cater to your every need, from arranging private yoga sessions to preparing delicious local cuisine.',
    host: {
      name: 'Wayan',
      avatarUrl: 'properties/beach-villa.png',
      joinDate: '2017-02-20',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'TV', icon: 'tv' },
      { name: 'Iron', icon: 'iron' },
      { name: 'Hair dryer', icon: 'dryer' },
      { name: 'Washer', icon: 'local_laundry_service' },
      { name: 'Dryer', icon: 'local_laundry_service' },
      { name: 'Hot water', icon: 'hot_tub' },
      { name: 'Pool', icon: 'pool' },
      { name: 'Private entrance', icon: 'meeting_room' },
      { name: 'Shampoo', icon: 'wash' },
      { name: 'Conditioner', icon: 'wash' },
      { name: 'Shower gel', icon: 'wash' },
      { name: 'Bed linens', icon: 'bed' },
      { name: 'Extra pillows and blankets', icon: 'bed' },
      { name: 'Hangers', icon: 'hanger' },
      { name: 'Smoke alarm', icon: 'smoke_free' },
      { name: 'Carbon monoxide alarm', icon: 'smoke_free' },
      { name: 'First aid kit', icon: 'medical_services' },
      { name: 'Fire extinguisher', icon: 'fire_extinguisher' },
      { name: 'Dishes and silverware', icon: 'restaurant' },
      { name: 'Cooking basics', icon: 'soup_kitchen' },
      { name: 'Oven', icon: 'oven' },
      { name: 'Stove', icon: 'stove' },
      { name: 'Refrigerator', icon: 'kitchen' },
      { name: 'Dishwasher', icon: 'dishwasher' },
      { name: 'Coffee maker', icon: 'coffee_maker' },
      { name: 'Microwave', icon: 'microwave' },
      { name: 'Toaster', icon: 'toaster' },
      { name: 'Blender', icon: 'blender' },
      { name: 'Barbecue utensils', icon: 'outdoor_grill' },
      { name: 'Dining table', icon: 'restaurant' },
      { name: 'Patio or balcony', icon: 'balcony' },
      { name: 'Backyard', icon: 'yard' },
      { name: 'Outdoor furniture', icon: 'deck' },
      { name: 'BBQ grill', icon: 'outdoor_grill' },
      { name: 'Beach access', icon: 'waves' },
      { name: 'Ocean views', icon: 'ocean' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
      { text: 'No parties or events', allowed: false },
      { text: 'Check-in is anytime after 4 PM', allowed: true },
      { text: 'Check-out by 12 PM', allowed: true },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in and get a full refund. Cancel up to 14 days before check-in and get a 50% refund.' },
    ],
    reviews: [
      {
        author: { name: 'David', avatarUrl: 'properties/beach-villa.png' },
        date: '2023-11-05',
        rating: 5,
        text: 'This villa is absolute paradise! The photos don\'t do it justice. The private pool and beach access were incredible. The staff was so friendly and helpful. We can\'t wait to come back!',
      },
      {
        author: { name: 'Emily', avatarUrl: 'properties/beach-villa-2.png' },
        date: '2023-10-22',
        rating: 5,
        text: 'A truly luxurious experience. The villa was spotless, the beds were comfortable, and the views were breathtaking. Wayan was an amazing host. Worth every penny!',
      },
      {
        author: { name: 'Frank', avatarUrl: 'properties/beach-villa-3.png' },
        date: '2023-09-18',
        rating: 4,
        text: 'We had a fantastic stay. The location is perfect, right on the beach. The only minor issue was that the air conditioning in one of the bedrooms was a bit noisy.',
      },
    ],
    coverImg: {
      url: 'properties/beach-villa.png',
      alt: 'A luxurious beachfront villa in Bali with a private infinity pool.',
    },
    imgs: [
      { url: 'properties/beach-villa.png', alt: 'The villa\'s exterior with the infinity pool overlooking the ocean.' },
      { url: 'properties/beach-villa-2.png', alt: 'The spacious living area with floor-to-ceiling windows and ocean views.' },
      { url: 'properties/beach-villa-3.png', alt: 'The master bedroom with a king-sized bed and a private balcony.' },
      { url: 'properties/beach-villa.png', alt: 'The outdoor dining area, perfect for enjoying meals with a view.' },
    ],
  },
  {
    id: '3',
    title: 'Traditional Japanese Machiya',
    location: 'Kyoto, Japan',
    pricePerNight: 300,
    rating: 4.9,
    reviewCount: 180,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    description: 'Experience the charm of old Kyoto in our beautifully restored machiya. This traditional wooden townhouse combines authentic Japanese design with modern comforts. Relax in the private garden, sleep on comfortable futons, and immerse yourself in the local culture. Located in the historic Gion district, you\'ll be just steps away from temples, shrines, and traditional tea houses.',
    host: {
      name: 'Yuki',
      avatarUrl: 'properties/japanese-house.png',
      joinDate: '2019-01-15',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'TV', icon: 'tv' },
      { name: 'Iron', icon: 'iron' },
      { name: 'Hair dryer', icon: 'dryer' },
      { name: 'Washer', icon: 'local_laundry_service' },
      { name: 'Dryer', icon: 'local_laundry_service' },
      { name: 'Hot water', icon: 'hot_tub' },
      { name: 'Private entrance', icon: 'meeting_room' },
      { name: 'Shampoo', icon: 'wash' },
      { name: 'Conditioner', icon: 'wash' },
      { name: 'Shower gel', icon: 'wash' },
      { name: 'Bed linens', icon: 'bed' },
      { name: 'Extra pillows and blankets', icon: 'bed' },
      { name: 'Hangers', icon: 'hanger' },
      { name: 'Smoke alarm', icon: 'smoke_free' },
      { name: 'Carbon monoxide alarm', icon: 'smoke_free' },
      { name: 'First aid kit', icon: 'medical_services' },
      { name: 'Fire extinguisher', icon: 'fire_extinguisher' },
      { name: 'Dishes and silverware', icon: 'restaurant' },
      { name: 'Cooking basics', icon: 'soup_kitchen' },
      { name: 'Refrigerator', icon: 'kitchen' },
      { name: 'Coffee maker', icon: 'coffee_maker' },
      { name: 'Microwave', icon: 'microwave' },
      { name: 'Toaster', icon: 'toaster' },
      { name: 'Dining table', icon: 'restaurant' },
      { name: 'Garden', icon: 'yard' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
      { text: 'No parties or events', allowed: false },
      { text: 'Please take off your shoes inside', allowed: true },
      { text: 'Check-in is anytime after 3 PM', allowed: true },
      { text: 'Check-out by 10 AM', allowed: true },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in and get a full refund. Cancel up to 7 days before check-in and get a 50% refund.' },
    ],
    reviews: [
      {
        author: { name: 'Grace', avatarUrl: 'properties/japanese-house.png' },
        date: '2023-10-30',
        rating: 5,
        text: 'Staying in this machiya was a truly special experience. It was like stepping back in time, but with all the modern conveniences. The location in Gion was perfect for exploring. Yuki was a wonderful host!',
      },
      {
        author: { name: 'Henry', avatarUrl: 'properties/japanese-house-2.png' },
        date: '2023-09-25',
        rating: 5,
        text: 'An unforgettable stay. The machiya is beautifully preserved and the private garden is a peaceful oasis. We loved sleeping on the futons. Highly recommended for an authentic Kyoto experience.',
      },
      {
        author: { name: 'Isabella', avatarUrl: 'properties/japanese-house-3.png' },
        date: '2023-08-20',
        rating: 4,
        text: 'A charming and unique place to stay. The location is fantastic. The stairs to the second floor are quite steep, which might be a challenge for some, but it adds to the authenticity.',
      },
    ],
    coverImg: {
      url: 'properties/japanese-house.png',
      alt: 'A traditional Japanese machiya in Kyoto with a private garden.',
    },
    imgs: [
      { url: 'properties/japanese-house.png', alt: 'The exterior of the machiya with its wooden lattice work.' },
      { url: 'properties/japanese-house-2.png', alt: 'The tatami mat room with sliding paper doors.' },
      { url: 'properties/japanese-house-3.png', alt: 'The serene private garden with a stone lantern.' },
      { url: 'properties/japanese-house.png', alt: 'The modern bathroom with a deep soaking tub.' },
    ],
  },
  {
    id: '4',
    title: 'Stylish Loft in the Heart of the City',
    location: 'New York, New York',
    pricePerNight: 400,
    rating: 4.7,
    reviewCount: 300,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'Live like a true New Yorker in our stylish loft in the vibrant East Village. With its high ceilings, exposed brick walls, and large windows, this apartment is the perfect urban retreat. You\'ll be surrounded by the city\'s best restaurants, bars, and shops, and just a short walk from several subway lines. The apartment is fully equipped with everything you need for a comfortable stay, including a gourmet kitchen and a luxurious queen-sized bed.',
    host: {
      name: 'Michael',
      avatarUrl: 'properties/city-loft.png',
      joinDate: '2016-11-08',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'TV', icon: 'tv' },
      { name: 'Iron', icon: 'iron' },
      { name: 'Hair dryer', icon: 'dryer' },
      { name: 'Washer', icon: 'local_laundry_service' },
      { name: 'Dryer', icon: 'local_laundry_service' },
      { name: 'Hot water', icon: 'hot_tub' },
      { name: 'Elevator', icon: 'elevator' },
      { name: 'Private entrance', icon: 'meeting_room' },
      { name: 'Shampoo', icon: 'wash' },
      { name: 'Conditioner', icon: 'wash' },
      { name: 'Shower gel', icon: 'wash' },
      { name: 'Bed linens', icon: 'bed' },
      { name: 'Extra pillows and blankets', icon: 'bed' },
      { name: 'Hangers', icon: 'hanger' },
      { name: 'Smoke alarm', icon: 'smoke_free' },
      { name: 'Carbon monoxide alarm', icon: 'smoke_free' },
      { name: 'First aid kit', icon: 'medical_services' },
      { name: 'Fire extinguisher', icon: 'fire_extinguisher' },
      { name: 'Dishes and silverware', icon: 'restaurant' },
      { name: 'Cooking basics', icon: 'soup_kitchen' },
      { name: 'Oven', icon: 'oven' },
      { name: 'Stove', icon: 'stove' },
      { name: 'Refrigerator', icon: 'kitchen' },
      { name: 'Dishwasher', icon: 'dishwasher' },
      { name: 'Coffee maker', icon: 'coffee_maker' },
      { name: 'Microwave', icon: 'microwave' },
      { name: 'Toaster', icon: 'toaster' },
      { name: 'Blender', icon: 'blender' },
      { name: 'Dining table', icon: 'restaurant' },
      { name: 'City views', icon: 'location_city' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
      { text: 'No parties or events', allowed: false },
      { text: 'Check-in is anytime after 4 PM', allowed: true },
      { text: 'Check-out by 11 AM', allowed: true },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 7 days before check-in and get a full refund. After that, no refund.' },
    ],
    reviews: [
      {
        author: { name: 'Jessica', avatarUrl: 'properties/city-loft.png' },
        date: '2023-11-10',
        rating: 5,
        text: 'This loft is amazing! The location is unbeatable, and the apartment itself is spacious, clean, and beautifully decorated. Michael was a great host and gave us some fantastic restaurant recommendations.',
      },
      {
        author: { name: 'Kevin', avatarUrl: 'properties/city-loft.png' },
        date: '2023-10-25',
        rating: 4,
        text: 'A great place to stay in the heart of the East Village. The apartment was comfortable and had everything we needed. It can be a bit noisy at night, but that\'s to be expected in such a lively neighborhood.',
      },
      {
        author: { name: 'Laura', avatarUrl: 'properties/city-loft.png' },
        date: '2023-09-30',
        rating: 5,
        text: 'We loved our stay here! The loft is even better than the pictures. The high ceilings and large windows make it feel so bright and airy. We would definitely stay here again.',
      },
    ],
    coverImg: {
      url: 'properties/city-loft.png',
      alt: 'A stylish loft in New York City with high ceilings and exposed brick walls.',
    },
    imgs: [
      { url: 'properties/city-loft.png', alt: 'The living area with a comfortable sofa and a view of the city.' },
      { url: 'properties/city-loft.png', alt: 'The gourmet kitchen with stainless steel appliances.' },
      { url: 'properties/city-loft.png', alt: 'The bedroom with a queen-sized bed and a large window.' },
      { url: 'properties/city-loft.png', alt: 'The modern bathroom with a walk-in shower.' },
    ],
  },
  {
    id: '5',
    title: 'Sunny Beachfront Condo',
    location: 'Miami, Florida',
    pricePerNight: 350,
    rating: 4.9,
    reviewCount: 180,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    description: 'Wake up to the sound of waves in our stunning beachfront condo in the heart of South Beach. This modern and spacious apartment offers breathtaking ocean views, a private balcony, and direct access to the beach. Enjoy the vibrant nightlife, world-class restaurants, and designer shops, all just steps away. The building features a large swimming pool, a fully-equipped gym, and 24-hour security.',
    host: {
      name: 'Maria',
      avatarUrl: 'properties/beach-villa.png',
      joinDate: '2018-08-15',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'TV', icon: 'tv' },
      { name: 'Iron', icon: 'iron' },
      { name: 'Hair dryer', icon: 'dryer' },
      { name: 'Washer', icon: 'local_laundry_service' },
      { name: 'Dryer', icon: 'local_laundry_service' },
      { name: 'Hot water', icon: 'hot_tub' },
      { name: 'Pool', icon: 'pool' },
      { name: 'Gym', icon: 'fitness_center' },
      { name: 'Elevator', icon: 'elevator' },
      { name: 'Private entrance', icon: 'meeting_room' },
      { name: 'Shampoo', icon: 'wash' },
      { name: 'Conditioner', icon: 'wash' },
      { name: 'Shower gel', icon: 'wash' },
      { name: 'Bed linens', icon: 'bed' },
      { name: 'Extra pillows and blankets', icon: 'bed' },
      { name: 'Hangers', icon: 'hanger' },
      { name: 'Smoke alarm', icon: 'smoke_free' },
      { name: 'Carbon monoxide alarm', icon: 'smoke_free' },
      { name: 'First aid kit', icon: 'medical_services' },
      { name: 'Fire extinguisher', icon: 'fire_extinguisher' },
      { name: 'Dishes and silverware', icon: 'restaurant' },
      { name: 'Cooking basics', icon: 'soup_kitchen' },
      { name: 'Oven', icon: 'oven' },
      { name: 'Stove', icon: 'stove' },
      { name: 'Refrigerator', icon: 'kitchen' },
      { name: 'Dishwasher', icon: 'dishwasher' },
      { name: 'Coffee maker', icon: 'coffee_maker' },
      { name: 'Microwave', icon: 'microwave' },
      { name: 'Toaster', icon: 'toaster' },
      { name: 'Blender', icon: 'blender' },
      { name: 'Dining table', icon: 'restaurant' },
      { name: 'Patio or balcony', icon: 'balcony' },
      { name: 'Beach access', icon: 'waves' },
      { name: 'Ocean views', icon: 'ocean' }
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
      { text: 'No parties or events', allowed: false },
      { text: 'Check-in is anytime after 4 PM', allowed: true },
      { text: 'Check-out by 11 AM', allowed: true }
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in and get a full refund. Cancel up to 7 days before check-in and get a 50% refund.' }
    ],
    reviews: [
      {
        author: { name: 'Olivia', avatarUrl: 'properties/beach-villa.png' },
        date: '2023-11-12',
        rating: 5,
        text: 'This condo is a dream! The location is perfect, the views are incredible, and the apartment is beautifully decorated. We loved having direct beach access and the pool was a great bonus. Maria was a fantastic host!',
      },
      {
        author: { name: 'Peter', avatarUrl: 'properties/beach-villa-2.png' },
        date: '2023-10-28',
        rating: 5,
        text: 'An amazing place to stay in South Beach. The condo was spotless and had everything we needed. The balcony was our favorite spot to relax and watch the ocean. Highly recommend!',
      },
      {
        author: { name: 'Quinn', avatarUrl: 'properties/beach-villa-3.png' },
        date: '2023-09-22',
        rating: 4,
        text: 'We had a great time. The location is unbeatable. The only small issue was that the elevator was a bit slow at times, but it was a minor inconvenience.',
      }
    ],
    coverImg: {
      url: 'properties/beach-villa.png',
      alt: 'A sunny beachfront condo in Miami with a view of the ocean.',
    },
    imgs: [
      { url: 'properties/beach-villa.png', alt: 'The living room with a large window overlooking the beach.' },
      { url: 'properties/beach-villa-2.png', alt: 'The modern kitchen with stainless steel appliances.' },
      { url: 'properties/beach-villa-3.png', alt: 'The bedroom with a king-sized bed and a private balcony.' },
      { url: 'properties/beach-villa.png', alt: 'The view from the balcony, showing the beach and the ocean.' },
    ],
  },
  {
    id: '6',
    title: 'Rustic Cabin in the Smoky Mountains',
    location: 'Gatlinburg, Tennessee',
    pricePerNight: 200,
    rating: 4.8,
    reviewCount: 150,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    description: 'Experience the beauty of the Great Smoky Mountains in our authentic log cabin. This cozy retreat is perfect for families or groups of friends looking to explore the national park. Enjoy the stunning mountain views from the hot tub on the deck, or curl up by the fireplace with a good book. The cabin is just a short drive from downtown Gatlinburg and all its attractions.',
    host: {
      name: 'David',
      avatarUrl: 'properties/mountain-cabin.png',
      joinDate: '2019-03-10',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'TV', icon: 'tv' },
      { name: 'Iron', icon: 'iron' },
      { name: 'Hair dryer', icon: 'dryer' },
      { name: 'Washer', icon: 'local_laundry_service' },
      { name: 'Dryer', icon: 'local_laundry_service' },
      { name: 'Hot water', icon: 'hot_tub' },
      { name: 'Hot tub', icon: 'hot_tub' },
      { name: 'Fireplace', icon: 'fireplace' },
      { name: 'Private entrance', icon: 'meeting_room' },
      { name: 'Shampoo', icon: 'wash' },
      { name: 'Conditioner', icon: 'wash' },
      { name: 'Shower gel', icon: 'wash' },
      { name: 'Bed linens', icon: 'bed' },
      { name: 'Extra pillows and blankets', icon: 'bed' },
      { name: 'Hangers', icon: 'hanger' },
      { name: 'Smoke alarm', icon: 'smoke_free' },
      { name: 'Carbon monoxide alarm', icon: 'smoke_free' },
      { name: 'First aid kit', icon: 'medical_services' },
      { name: 'Fire extinguisher', icon: 'fire_extinguisher' },
      { name: 'Dishes and silverware', icon: 'restaurant' },
      { name: 'Cooking basics', icon: 'soup_kitchen' },
      { name: 'Oven', icon: 'oven' },
      { name: 'Stove', icon: 'stove' },
      { name: 'Refrigerator', icon: 'kitchen' },
      { name: 'Dishwasher', icon: 'dishwasher' },
      { name: 'Coffee maker', icon: 'coffee_maker' },
      { name: 'Microwave', icon: 'microwave' },
      { name: 'Toaster', icon: 'toaster' },
      { name: 'Blender', icon: 'blender' },
      { name: 'Barbecue utensils', icon: 'outdoor_grill' },
      { name: 'Dining table', icon: 'restaurant' },
      { name: 'Patio or balcony', icon: 'balcony' },
      { name: 'Backyard', icon: 'yard' },
      { name: 'Outdoor furniture', icon: 'deck' },
      { name: 'BBQ grill', icon: 'outdoor_grill' },
      { name: 'Mountain views', icon: 'terrain' }
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
      { text: 'No parties or events', allowed: false },
      { text: 'Check-in is anytime after 4 PM', allowed: true },
      { text: 'Check-out by 10 AM', allowed: true }
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in and get a full refund. Cancel up to 7 days before check-in and get a 50% refund.' }
    ],
    reviews: [
      {
        author: { name: 'Rachel', avatarUrl: 'properties/mountain-cabin.png' },
        date: '2023-11-08',
        rating: 5,
        text: 'This cabin was perfect for our family vacation! The kids loved the hot tub, and we loved the beautiful mountain views. The location is great, close to both the national park and downtown Gatlinburg. David was a very helpful host!',
      },
      {
        author: { name: 'Steve', avatarUrl: 'properties/mountain-cabin-2.png' },
        date: '2023-10-20',
        rating: 5,
        text: 'A wonderful and cozy cabin. It was very clean and well-maintained. The fireplace was a nice touch, especially on the chilly evenings. We would definitely stay here again.',
      },
      {
        author: { name: 'Tina', avatarUrl: 'properties/mountain-cabin-3.png' },
        date: '2023-09-15',
        rating: 4,
        text: 'We had a great stay. The cabin is in a beautiful and peaceful location. The driveway is a bit steep, but our car handled it fine. The wifi was a little slow, but we didn\'t mind.',
      }
    ],
    coverImg: {
      url: 'properties/mountain-cabin.png',
      alt: 'A rustic cabin in the Smoky Mountains with a view of the surrounding forest.',
    },
    imgs: [
      { url: 'properties/mountain-cabin.png', alt: 'The exterior of the log cabin with a large deck.' },
      { url: 'properties/mountain-cabin-2.png', alt: 'The living room with a stone fireplace and comfortable furniture.' },
      { url: 'properties/mountain-cabin-3.png', alt: 'The hot tub on the deck with a view of the mountains.' },
      { url: 'properties/mountain-cabin.png', alt: 'One of the bedrooms with a queen-sized bed and rustic decor.' },
    ],
  },
  {
    id: '7',
    title: 'Modern Apartment in the Windy City',
    location: 'Chicago, Illinois',
    pricePerNight: 300,
    rating: 4.7,
    reviewCount: 200,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    description: 'Explore Chicago from our stylish and modern apartment in the trendy River North neighborhood. With its floor-to-ceiling windows, you\'ll enjoy stunning views of the city skyline. The apartment is just steps away from the city\'s best restaurants, bars, and art galleries. The building features a rooftop pool, a state-of-the-art gym, and a 24-hour doorman.',
    host: {
      name: 'Jennifer',
      avatarUrl: 'properties/city-loft.png',
      joinDate: '2017-05-25',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'TV', icon: 'tv' },
      { name: 'Iron', icon: 'iron' },
      { name: 'Hair dryer', icon: 'dryer' },
      { name: 'Washer', icon: 'local_laundry_service' },
      { name: 'Dryer', icon: 'local_laundry_service' },
      { name: 'Hot water', icon: 'hot_tub' },
      { name: 'Pool', icon: 'pool' },
      { name: 'Gym', icon: 'fitness_center' },
      { name: 'Elevator', icon: 'elevator' },
      { name: 'Private entrance', icon: 'meeting_room' },
      { name: 'Shampoo', icon: 'wash' },
      { name: 'Conditioner', icon: 'wash' },
      { name: 'Shower gel', icon: 'wash' },
      { name: 'Bed linens', icon: 'bed' },
      { name: 'Extra pillows and blankets', icon: 'bed' },
      { name: 'Hangers', icon: 'hanger' },
      { name: 'Smoke alarm', icon: 'smoke_free' },
      { name: 'Carbon monoxide alarm', icon: 'smoke_free' },
      { name: 'First aid kit', icon: 'medical_services' },
      { name: 'Fire extinguisher', icon: 'fire_extinguisher' },
      { name: 'Dishes and silverware', icon: 'restaurant' },
      { name: 'Cooking basics', icon: 'soup_kitchen' },
      { name: 'Oven', icon: 'oven' },
      { name: 'Stove', icon: 'stove' },
      { name: 'Refrigerator', icon: 'kitchen' },
      { name: 'Dishwasher', icon: 'dishwasher' },
      { name: 'Coffee maker', icon: 'coffee_maker' },
      { name: 'Microwave', icon: 'microwave' },
      { name: 'Toaster', icon: 'toaster' },
      { name: 'Blender', icon: 'blender' },
      { name: 'Dining table', icon: 'restaurant' },
      { name: 'City views', icon: 'location_city' }
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
      { text: 'No parties or events', allowed: false },
      { text: 'Check-in is anytime after 3 PM', allowed: true },
      { text: 'Check-out by 11 AM', allowed: true }
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 7 days before check-in and get a full refund. After that, no refund.' }
    ],
    reviews: [
      {
        author: { name: 'Uma', avatarUrl: 'properties/city-loft.png' },
        date: '2023-11-15',
        rating: 5,
        text: 'This apartment is absolutely stunning! The views are even better in person. The location is perfect for exploring the city. Jennifer was a great host and provided us with a list of her favorite local spots.',
      },
      {
        author: { name: 'Victor', avatarUrl: 'properties/city-loft.png' },
        date: '2023-10-30',
        rating: 5,
        text: 'A fantastic place to stay in Chicago. The apartment was clean, modern, and had everything we needed. The rooftop pool was a huge plus. We would definitely stay here again.',
      },
      {
        author: { name: 'Wendy', avatarUrl: 'properties/city-loft.png' },
        date: '2023-09-28',
        rating: 4,
        text: 'We had a great time. The apartment is in a very convenient location. The only downside was that the street noise was a bit loud at times, but that\'s to be expected in a big city.',
      }
    ],
    coverImg: {
      url: 'properties/city-loft.png',
      alt: 'A modern apartment in Chicago with a view of the city skyline.',
    },
    imgs: [
      { url: 'properties/city-loft.png', alt: 'The living room with floor-to-ceiling windows and a view of the city.' },
      { url: 'properties/city-loft.png', alt: 'The sleek and modern kitchen with high-end appliances.' },
      { url: 'properties/city-loft.png', alt: 'The bedroom with a king-sized bed and a stunning city view.' },
      { url: 'properties/city-loft.png', alt: 'The rooftop pool with lounge chairs and a panoramic view of the city.' },
    ],
  },
];

export const SUBSET_LISTINGS: Listing[] = [
  {
    id: '8',
    title: 'Secluded Treehouse with Hot Tub',
    location: 'Asheville, North Carolina',
    pricePerNight: 350,
    rating: 4.9,
    reviewCount: 210,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'Rekindle the romance in this magical treehouse escape. Nestled in a private forest, this stunning retreat offers a hot tub on the deck, a cozy fireplace, and breathtaking views of the Blue Ridge Mountains. Perfect for honeymoons, anniversaries, or just a quiet getaway.',
    host: {
      name: 'Sarah',
      avatarUrl: 'properties/treehouse.png',
      joinDate: '2020-02-14',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchenette', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'Hot tub', icon: 'hot_tub' },
      { name: 'Fireplace', icon: 'fireplace' },
      { name: 'Private entrance', icon: 'meeting_room' },
      { name: 'Mountain views', icon: 'terrain' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
      { text: 'No parties or events', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/treehouse.png',
      alt: 'A romantic treehouse in the forest.',
    },
    imgs: [
        { url: 'properties/treehouse.png', alt: 'A romantic treehouse in the forest.' },
        { url: 'properties/treehouse-2.png', alt: 'A romantic treehouse in the forest.' },
    ],
  },
  {
    id: '9',
    title: 'Oceanfront Cottage for Two',
    location: 'Cannon Beach, Oregon',
    pricePerNight: 400,
    rating: 4.95,
    reviewCount: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A charming cottage right on the beach with stunning views of Haystack Rock. This is the perfect spot for a romantic escape. Enjoy long walks on the beach, watch the sunset from your private deck, and fall asleep to the sound of the waves.',
    host: {
      name: 'Tom',
      avatarUrl: 'properties/beach-villa.png',
      joinDate: '2019-06-22',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'TV', icon: 'tv' },
      { name: 'Fireplace', icon: 'fireplace' },
      { name: 'Beach access', icon: 'waves' },
      { name: 'Ocean views', icon: 'ocean' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/beach-villa.png',
      alt: 'A cozy cottage on the beach.',
    },
    imgs: [
        { url: 'properties/beach-villa.png', alt: 'A cozy cottage on the beach.' },
        { url: 'properties/beach-villa-2.png', alt: 'A cozy cottage on the beach.' },
        { url: 'properties/beach-villa-3.png', alt: 'A cozy cottage on the beach.' },
    ],
  },
  {
    id: '10',
    title: 'Vineyard Villa with Private Pool',
    location: 'Napa Valley, California',
    pricePerNight: 600,
    rating: 5.0,
    reviewCount: 150,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'Indulge in a luxurious getaway at our private villa in the heart of wine country. Surrounded by vineyards, this elegant retreat features a private pool, a gourmet kitchen, and a romantic outdoor dining area. Spend your days wine tasting and your evenings relaxing in style.',
    host: {
      name: 'Isabella',
      avatarUrl: 'properties/tuscan-villa.png',
      joinDate: '2018-10-01',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Pool', icon: 'pool' },
      { name: 'Hot tub', icon: 'hot_tub' },
      { name: 'Fireplace', icon: 'fireplace' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/tuscan-villa.png',
      alt: 'A luxurious villa in a vineyard.',
    },
    imgs: [
        { url: 'properties/tuscan-villa.png', alt: 'A luxurious villa in a vineyard.' },
    ],
  },
  {
    id: '11',
    title: 'Charming Parisian Apartment',
    location: 'Paris, France',
    pricePerNight: 250,
    rating: 4.8,
    reviewCount: 300,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'Live like a local in our romantic apartment in the heart of Le Marais. With its classic Parisian charm, including a small balcony overlooking the street, this is the perfect base for exploring the City of Love. Just steps away from charming cafes, boutiques, and museums.',
    host: {
      name: 'Juliette',
      avatarUrl: 'properties/city-loft.png',
      joinDate: '2017-04-11',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'Washer', icon: 'local_laundry_service' },
      { name: 'Elevator', icon: 'elevator' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 7 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/city-loft.png',
      alt: 'A charming apartment in Paris.',
    },
    imgs: [
        { url: 'properties/city-loft.png', alt: 'A charming apartment in Paris.' },
    ],
  },
  {
    id: '12',
    title: 'Lakeside Cabin with Private Dock',
    location: 'Lake Placid, New York',
    pricePerNight: 300,
    rating: 4.9,
    reviewCount: 190,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A serene and romantic cabin on the shores of Lake Placid. Enjoy swimming, kayaking, and fishing from your private dock. In the evening, cozy up by the fire pit and watch the stars. This is the perfect place to disconnect and reconnect with your partner.',
    host: {
      name: 'Bill',
      avatarUrl: 'properties/lake-house.png',
      joinDate: '2019-08-01',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'Fireplace', icon: 'fireplace' },
      { name: 'Lake access', icon: 'waves' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'Pets allowed', allowed: true },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/lake-house.png',
      alt: 'A cabin on the lake.',
    },
    imgs: [
        { url: 'properties/lake-house.png', alt: 'A cabin on the lake.' },
    ],
  },
  {
    id: '13',
    title: 'Desert Oasis with Stargazing Dome',
    location: 'Joshua Tree, California',
    pricePerNight: 450,
    rating: 4.98,
    reviewCount: 250,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'An unforgettable experience in the desert. This unique home features a stargazing dome, a hot tub, and a fire pit. The modern and minimalist design blends seamlessly with the natural landscape. Perfect for a romantic and spiritual retreat.',
    host: {
      name: 'Luna',
      avatarUrl: 'properties/desert-oasis.png',
      joinDate: '2021-01-10',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Hot tub', icon: 'hot_tub' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/desert-oasis.png',
      alt: 'A modern home in the desert.',
    },
    imgs: [
        { url: 'properties/desert-oasis.png', alt: 'A modern home in the desert.' },
        { url: 'properties/desert-oasis-2.png', alt: 'A modern home in the desert.' },
    ],
  },
  {
    id: '14',
    title: 'Historic Carriage House',
    location: 'Savannah, Georgia',
    pricePerNight: 280,
    rating: 4.85,
    reviewCount: 220,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'Step back in time in this beautifully restored carriage house in the heart of Savannah\'s historic district. With its private courtyard, antique furnishings, and romantic atmosphere, this is the perfect spot for a southern getaway.',
    host: {
      name: 'Eleanor',
      avatarUrl: 'properties/historic-house.png',
      joinDate: '2018-03-15',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Air conditioning', icon: 'ac_unit' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 7 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/historic-house.png',
      alt: 'A historic carriage house.',
    },
    imgs: [
        { url: 'properties/historic-house.png', alt: 'A historic carriage house.' },
    ],
  },
  {
    id: '15',
    title: 'Cozy A-Frame in the Woods',
    location: 'Leavenworth, Washington',
    pricePerNight: 250,
    rating: 4.9,
    reviewCount: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A charming and cozy A-frame cabin nestled in the woods. Perfect for a romantic weekend away from the city. Enjoy the hot tub, the fireplace, and the peaceful sounds of nature. Just a short drive from the Bavarian-themed town of Leavenworth.',
    host: {
      name: 'Mark',
      avatarUrl: 'properties/mountain-cabin.png',
      joinDate: '2020-09-01',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'Hot tub', icon: 'hot_tub' },
      { name: 'Fireplace', icon: 'fireplace' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/mountain-cabin.png',
      alt: 'An A-frame cabin in the woods.',
    },
    imgs: [
        { url: 'properties/mountain-cabin.png', alt: 'An A-frame cabin in the woods.' },
        { url: 'properties/mountain-cabin-2.png', alt: 'An A-frame cabin in the woods.' },
        { url: 'properties/mountain-cabin-3.png', alt: 'An A-frame cabin in the woods.' },
    ],
  },
  {
    id: '16',
    title: 'Tuscan Farmhouse with a View',
    location: 'Tuscany, Italy',
    pricePerNight: 300,
    rating: 4.95,
    reviewCount: 200,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'Experience the magic of Tuscany in our beautifully restored farmhouse. With stunning views of the rolling hills, a private garden, and a swimming pool, this is the perfect place for a romantic and relaxing vacation. Enjoy cooking with fresh local ingredients in the fully-equipped kitchen.',
    host: {
      name: 'Giulia',
      avatarUrl: 'properties/tuscan-villa.png',
      joinDate: '2017-07-20',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Pool', icon: 'pool' },
      { name: 'Fireplace', icon: 'fireplace' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/tuscan-villa.png',
      alt: 'A farmhouse in Tuscany.',
    },
    imgs: [
        { url: 'properties/tuscan-villa.png', alt: 'A farmhouse in Tuscany.' },
    ],
  },
  {
    id: '17',
    title: 'Santorini Cave House with Caldera View',
    location: 'Oia, Santorini, Greece',
    pricePerNight: 500,
    rating: 5.0,
    reviewCount: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A traditional cave house perched on the cliffs of Oia with a breathtaking view of the caldera. This is the ultimate romantic destination. Enjoy the sunset from your private hot tub on the terrace. An unforgettable experience.',
    host: {
      name: 'Nikos',
      avatarUrl: 'properties/beach-villa-3.png',
      joinDate: '2018-05-10',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchenette', icon: 'kitchen' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Hot tub', icon: 'hot_tub' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/beach-villa-3.png',
      alt: 'A cave house in Santorini.',
    },
    imgs: [
        { url: 'properties/beach-villa-3.png', alt: 'A cave house in Santorini.' },
    ],
  },
  {
    id: '18',
    title: 'Glamping Yurt under the Stars',
    location: 'Moab, Utah',
    pricePerNight: 200,
    rating: 4.9,
    reviewCount: 150,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A unique and romantic glamping experience in the desert. Our luxurious yurt is equipped with a comfortable bed, a private bathroom, and a kitchenette. At night, step outside and be amazed by the incredible stargazing opportunities.',
    host: {
      name: 'Alex',
      avatarUrl: 'properties/desert-oasis-2.png',
      joinDate: '2021-03-20',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Kitchenette', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Heating', icon: 'thermostat' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 7 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/desert-oasis-2.png',
      alt: 'A glamping yurt in the desert.',
    },
    imgs: [
        { url: 'properties/desert-oasis-2.png', alt: 'A glamping yurt in the desert.' },
    ],
  },
  {
    id: '19',
    title: 'Riverside Cabin with Sauna',
    location: 'Finland',
    pricePerNight: 280,
    rating: 4.95,
    reviewCount: 160,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A traditional Finnish cabin on the banks of a peaceful river. This is the perfect place to relax and rejuvenate. Enjoy the private sauna, take a dip in the river, and go for a walk in the surrounding forest. In the winter, you might even see the Northern Lights.',
    host: {
      name: 'Hanna',
      avatarUrl: 'properties/lake-house.png',
      joinDate: '2019-11-05',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'Sauna', icon: 'hot_tub' },
      { name: 'Fireplace', icon: 'fireplace' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/lake-house.png',
      alt: 'A cabin by a river in Finland.',
    },
    imgs: [
        { url: 'properties/lake-house.png', alt: 'A cabin by a river in Finland.' },
    ],
  },
  {
    id: '20',
    title: 'Bohemian Loft in Greenwich Village',
    location: 'New York, New York',
    pricePerNight: 320,
    rating: 4.8,
    reviewCount: 250,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A stylish and romantic loft in the heart of Greenwich Village. With its eclectic decor, cozy reading nook, and large windows, this is the perfect urban oasis for a couple. Explore the charming streets, cafes, and jazz clubs of this iconic neighborhood.',
    host: {
      name: 'Chloe',
      avatarUrl: 'properties/city-loft.png',
      joinDate: '2018-09-12',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Heating', icon: 'thermostat' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 7 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/city-loft.png',
      alt: 'A bohemian loft in New York City.',
    },
    imgs: [
        { url: 'properties/city-loft.png', alt: 'A bohemian loft in New York City.' },
    ],
  },
  {
    id: '21',
    title: 'Scottish Highlands Castle Gatehouse',
    location: 'Scottish Highlands, Scotland',
    pricePerNight: 400,
    rating: 4.98,
    reviewCount: 190,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'Live out your fairytale dreams in this historic castle gatehouse. This unique and romantic property features a spiral staircase, a four-poster bed, and a cozy fireplace. Explore the castle grounds and the stunning scenery of the Scottish Highlands.',
    host: {
      name: 'Fiona',
      avatarUrl: 'properties/historic-house.png',
      joinDate: '2019-02-28',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
      { name: 'Heating', icon: 'thermostat' },
      { name: 'Fireplace', icon: 'fireplace' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/historic-house.png',
      alt: 'A castle gatehouse in the Scottish Highlands.',
    },
    imgs: [
        { url: 'properties/historic-house.png', alt: 'A castle gatehouse in the Scottish Highlands.' },
    ],
  },
  {
    id: '22',
    title: 'Overwater Bungalow in the Maldives',
    location: 'Maldives',
    pricePerNight: 1200,
    rating: 5.0,
    reviewCount: 220,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'The ultimate romantic escape. Our luxurious overwater bungalow offers direct access to the crystal-clear turquoise waters of the Indian Ocean. Relax on your private deck, go for a swim or a snorkel, and enjoy the stunning sunsets. This is a once-in-a-lifetime experience.',
    host: {
      name: 'Aisha',
      avatarUrl: 'properties/beach-villa-2.png',
      joinDate: '2017-12-01',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Private deck', icon: 'deck' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 60 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/beach-villa-2.png',
      alt: 'An overwater bungalow in the Maldives.',
    },
    imgs: [
        { url: 'properties/beach-villa-2.png', alt: 'An overwater bungalow in the Maldives.' },
    ],
  },
  {
    id: '23',
    title: 'Geodesic Dome on a Volcano',
    location: 'Big Island, Hawaii',
    pricePerNight: 300,
    rating: 4.9,
    reviewCount: 170,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A truly unique and adventurous romantic getaway. Our geodesic dome is located on the slopes of a volcano, offering incredible views and a sense of seclusion. Explore the nearby volcano national park and come back to your cozy and modern dome.',
    host: {
      name: 'Kai',
      avatarUrl: 'properties/desert-oasis.png',
      joinDate: '2020-10-15',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchenette', icon: 'kitchen' },
      { name: 'Free parking', icon: 'local_parking' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/desert-oasis.png',
      alt: 'A geodesic dome on a volcano.',
    },
    imgs: [
        { url: 'properties/desert-oasis.png', alt: 'A geodesic dome on a volcano.' },
    ],
  },
  {
    id: '24',
    title: 'Rooftop Apartment with Eiffel Tower View',
    location: 'Paris, France',
    pricePerNight: 450,
    rating: 4.95,
    reviewCount: 280,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'The most romantic view in Paris. Our rooftop apartment features a private terrace with a stunning, unobstructed view of the Eiffel Tower. Enjoy a glass of champagne as you watch the tower sparkle at night. A truly magical experience.',
    host: {
      name: 'Antoine',
      avatarUrl: 'properties/city-loft.png',
      joinDate: '2018-02-20',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Elevator', icon: 'elevator' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/city-loft.png',
      alt: 'An apartment with a view of the Eiffel Tower.',
    },
    imgs: [
        { url: 'properties/city-loft.png', alt: 'An apartment with a view of the Eiffel Tower.' },
    ],
  },
  {
    id: '25',
    title: 'Luxury Safari Tent in the Serengeti',
    location: 'Serengeti, Tanzania',
    pricePerNight: 800,
    rating: 5.0,
    reviewCount: 150,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'An unforgettable safari experience. Our luxurious tented camp offers all the comforts of a hotel in the heart of the Serengeti. Wake up to the sounds of the wild, go on thrilling game drives, and enjoy romantic dinners under the stars.',
    host: {
      name: 'Juma',
      avatarUrl: 'properties/desert-oasis-2.png',
      joinDate: '2019-05-18',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Ensuite bathroom', icon: 'wash' },
      { name: 'Private deck', icon: 'deck' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 60 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/desert-oasis-2.png',
      alt: 'A luxury safari tent.',
    },
    imgs: [
        { url: 'properties/desert-oasis-2.png', alt: 'A luxury safari tent.' },
    ],
  },
  {
    id: '26',
    title: 'Canal House in Amsterdam',
    location: 'Amsterdam, Netherlands',
    pricePerNight: 300,
    rating: 4.8,
    reviewCount: 260,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A charming and historic canal house in the heart of Amsterdam. With its large windows overlooking the canal, this is the perfect spot for a romantic city break. Explore the city by bike, visit the world-class museums, and enjoy the cozy atmosphere of this unique home.',
    host: {
      name: 'Annelies',
      avatarUrl: 'properties/historic-house.png',
      joinDate: '2017-09-01',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Heating', icon: 'thermostat' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/historic-house.png',
      alt: 'A canal house in Amsterdam.',
    },
    imgs: [
        { url: 'properties/historic-house.png', alt: 'A canal house in Amsterdam.' },
    ],
  },
  {
    id: '27',
    title: 'Private Island Getaway',
    location: 'Fiji',
    pricePerNight: 2500,
    rating: 5.0,
    reviewCount: 100,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'The ultimate in luxury and privacy. Rent your own private island in the beautiful waters of Fiji. This is the perfect destination for a honeymoon or a truly special romantic getaway. A private chef and staff are included.',
    host: {
      name: 'Mana',
      avatarUrl: 'properties/beach-villa.png',
      joinDate: '2018-11-11',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Private beach', icon: 'waves' },
      { name: 'Pool', icon: 'pool' },
      { name: 'Private chef', icon: 'restaurant' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 90 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/beach-villa.png',
      alt: 'A private island in Fiji.',
    },
    imgs: [
        { url: 'properties/beach-villa.png', alt: 'A private island in Fiji.' },
    ],
  },
  {
    id: '28',
    title: 'Ice Hotel Room',
    location: 'Jukkasjärvi, Sweden',
    pricePerNight: 600,
    rating: 4.9,
    reviewCount: 120,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A once-in-a-lifetime experience. Sleep in a room made entirely of ice and snow. Each room is a unique work of art, designed and sculpted by artists from around the world. A truly magical and romantic winter adventure.',
    host: {
      name: 'ICEHOTEL',
      avatarUrl: 'properties/mountain-cabin-3.png',
      joinDate: '2010-12-01',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Thermal sleeping bags', icon: 'bed' },
      { name: 'Access to warm building', icon: 'hot_tub' },
    ],
    rules: [],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/mountain-cabin-3.png',
      alt: 'A room in an ice hotel.',
    },
    imgs: [
        { url: 'properties/mountain-cabin-3.png', alt: 'A room in an ice hotel.' },
    ],
  },
  {
    id: '29',
    title: 'Glass Igloo with Northern Lights View',
    location: 'Finnish Lapland, Finland',
    pricePerNight: 700,
    rating: 4.95,
    reviewCount: 200,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'Watch the Northern Lights from the comfort of your own bed in our glass igloo. This is one of the most romantic and magical experiences on earth. The igloo is heated and has a private bathroom.',
    host: {
      name: 'Levin Iglut',
      avatarUrl: 'properties/mountain-cabin-2.png',
      joinDate: '2015-10-10',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Heated glass roof', icon: 'thermostat' },
      { name: 'Private bathroom', icon: 'wash' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/mountain-cabin-2.png',
      alt: 'A glass igloo.',
    },
    imgs: [
        { url: 'properties/mountain-cabin-2.png', alt: 'A glass igloo.' },
    ],
  },
  {
    id: '30',
    title: 'Ryokan with Private Onsen',
    location: 'Hakone, Japan',
    pricePerNight: 500,
    rating: 4.9,
    reviewCount: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A traditional Japanese inn with a private hot spring bath (onsen). This is the perfect place to relax and experience Japanese hospitality. Enjoy a multi-course kaiseki dinner and a traditional Japanese breakfast.',
    host: {
      name: 'Yumi',
      avatarUrl: 'properties/japanese-house.png',
      joinDate: '2018-04-01',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Private onsen', icon: 'hot_tub' },
      { name: 'Kaiseki dinner', icon: 'restaurant' },
      { name: 'Japanese breakfast', icon: 'restaurant' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/japanese-house.png',
      alt: 'A Japanese ryokan.',
    },
    imgs: [
        { url: 'properties/japanese-house.png', alt: 'A Japanese ryokan.' },
        { url: 'properties/japanese-house-2.png', alt: 'A Japanese ryokan.' },
        { url: 'properties/japanese-house-3.png', alt: 'A Japanese ryokan.' },
    ],
  },
  {
    id: '31',
    title: 'Houseboat on the Kerala Backwaters',
    location: 'Kerala, India',
    pricePerNight: 250,
    rating: 4.8,
    reviewCount: 160,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A romantic and peaceful journey through the beautiful backwaters of Kerala on a traditional houseboat. Your private crew will cook delicious local meals for you as you glide past lush green rice paddies and charming villages.',
    host: {
      name: 'Rajesh',
      avatarUrl: 'properties/lake-house.png',
      joinDate: '2019-01-20',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Private chef', icon: 'restaurant' },
    ],
    rules: [],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 7 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/lake-house.png',
      alt: 'A houseboat in Kerala.',
    },
    imgs: [
        { url: 'properties/lake-house.png', alt: 'A houseboat in Kerala.' },
    ],
  },
  {
    id: '32',
    title: 'Cave Hotel in Cappadocia',
    location: 'Cappadocia, Turkey',
    pricePerNight: 300,
    rating: 4.9,
    reviewCount: 220,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A unique and romantic hotel room carved into the rock formations of Cappadocia. Wake up early to see the sky filled with hot air balloons. A truly magical and unforgettable experience.',
    host: {
      name: 'Fatima',
      avatarUrl: 'properties/desert-oasis.png',
      joinDate: '2018-06-15',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Turkish bath', icon: 'hot_tub' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/desert-oasis.png',
      alt: 'A cave hotel in Cappadocia.',
    },
    imgs: [
        { url: 'properties/desert-oasis.png', alt: 'A cave hotel in Cappadocia.' },
    ],
  },
  {
    id: '33',
    title: 'Riad in the Heart of Marrakech',
    location: 'Marrakech, Morocco',
    pricePerNight: 200,
    rating: 4.85,
    reviewCount: 240,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A peaceful and romantic oasis in the bustling medina of Marrakech. Our traditional riad features a beautiful courtyard with a fountain, a rooftop terrace with views of the Atlas Mountains, and delicious home-cooked Moroccan meals.',
    host: {
      name: 'Karim',
      avatarUrl: 'properties/historic-house.png',
      joinDate: '2017-11-25',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Pool', icon: 'pool' },
      { name: 'Air conditioning', icon: 'ac_unit' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 7 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/historic-house.png',
      alt: 'A riad in Marrakech.',
    },
    imgs: [
        { url: 'properties/historic-house.png', alt: 'A riad in Marrakech.' },
    ],
  },
  {
    id: '34',
    title: 'Shepherd\'s Hut in the English Countryside',
    location: 'Cotswolds, England',
    pricePerNight: 180,
    rating: 4.9,
    reviewCount: 150,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A cozy and romantic shepherd\'s hut in the picturesque Cotswolds. This is the perfect place for a peaceful and charming getaway. Enjoy walks in the countryside, visit quaint villages, and relax by the wood-burning stove.',
    host: {
      name: 'Rose',
      avatarUrl: 'properties/mountain-cabin.png',
      joinDate: '2020-08-10',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Kitchenette', icon: 'kitchen' },
      { name: 'Wood-burning stove', icon: 'fireplace' },
    ],
    rules: [
      { text: 'No pets', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 7 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/mountain-cabin.png',
      alt: 'A shepherd\'s hut in the Cotswolds.',
    },
    imgs: [
        { url: 'properties/mountain-cabin.png', alt: 'A shepherd\'s hut in the Cotswolds.' },
    ],
  },
  {
    id: '35',
    title: 'Mountain Chalet with Sauna',
    location: 'Zermatt, Switzerland',
    pricePerNight: 500,
    rating: 4.95,
    reviewCount: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A luxurious and romantic chalet in the Swiss Alps with stunning views of the Matterhorn. After a day of skiing or hiking, relax in the private sauna or cozy up by the fireplace. A truly unforgettable mountain experience.',
    host: {
      name: 'Hans',
      avatarUrl: 'properties/mountain-cabin.png',
      joinDate: '2018-12-20',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Sauna', icon: 'hot_tub' },
      { name: 'Fireplace', icon: 'fireplace' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/mountain-cabin.png',
      alt: 'A chalet in the Swiss Alps.',
    },
    imgs: [
        { url: 'properties/mountain-cabin.png', alt: 'A chalet in the Swiss Alps.' },
        { url: 'properties/mountain-cabin-2.png', alt: 'A chalet in the Swiss Alps.' },
        { url: 'properties/mountain-cabin-3.png', alt: 'A chalet in the Swiss Alps.' },
    ],
  },
  {
    id: '36',
    title: 'Jungle Villa with Private Waterfall',
    location: 'Ubud, Bali, Indonesia',
    pricePerNight: 400,
    rating: 4.98,
    reviewCount: 200,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A stunning and romantic villa nestled in the heart of the Balinese jungle. This unique property features a private waterfall and swimming hole. The open-air design allows you to feel at one with nature. A truly magical and spiritual retreat.',
    host: {
      name: 'Dewi',
      avatarUrl: 'properties/treehouse-2.png',
      joinDate: '2019-07-15',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Pool', icon: 'pool' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 14 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/treehouse-2.png',
      alt: 'A jungle villa in Bali.',
    },
    imgs: [
        { url: 'properties/treehouse-2.png', alt: 'A jungle villa in Bali.' },
    ],
  },
  {
    id: '37',
    title: 'Penthouse with Rooftop Hot Tub',
    location: 'Sydney, Australia',
    pricePerNight: 600,
    rating: 4.9,
    reviewCount: 210,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    description: 'A luxurious penthouse apartment with a private rooftop hot tub and stunning views of the Sydney Opera House and Harbour Bridge. This is the perfect place for a special occasion or a romantic city getaway. Enjoy the best of Sydney right at your doorstep.',
    host: {
      name: 'Liam',
      avatarUrl: 'properties/city-loft.png',
      joinDate: '2018-01-05',
      isSuperhost: true,
    },
    amenities: [
      { name: 'Wifi', icon: 'wifi' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Air conditioning', icon: 'ac_unit' },
      { name: 'Hot tub', icon: 'hot_tub' },
    ],
    rules: [
      { text: 'No smoking', allowed: false },
      { text: 'No parties or events', allowed: false },
    ],
    policies: [
      { title: 'Cancellation policy', content: 'Cancel up to 30 days before check-in for a full refund.' },
    ],
    reviews: [],
    coverImg: {
      url: 'properties/city-loft.png',
      alt: 'A penthouse in Sydney.',
    },
    imgs: [
        { url: 'properties/city-loft.png', alt: 'A penthouse in Sydney.' },
    ],
  },
];